function g(a){throw a;}var i=true,j=null,l=false;function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function ca(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,r=this;function da(a,b,c){a=a.split(".");c=c||r;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}}function ea(){}function fa(a){a.ka=function(){return a.Le||(a.Le=new a)}}
function ga(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function s(a){return ga(a)=="array"}function ha(a){var b=ga(a);return b=="array"||b=="object"&&typeof a.length=="number"}function t(a){return typeof a=="string"}function ia(a){return ga(a)=="function"}function ja(a){a=ga(a);return a=="object"||a=="array"||a=="function"}function ka(a){return a[la]||(a[la]=++ma)}var la="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ma=0;
function na(a){return a.call.apply(a.bind,arguments)}function oa(a,b){var c=b||r;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}}function pa(){pa=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?na:oa;return pa.apply(j,arguments)}
function qa(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}}var ra=Date.now||function(){return+new Date};function sa(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a}function v(a,b){function c(){}c.prototype=b.prototype;a.c=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ta(){var a=window.localStorage.getItem("nicknames");if(t(a))return a;else if(a===j)return"{}";else g("nicknames should only contain a JSON-formatted string")}function ua(){var a=window.JSON.parse(ta());if(!ja(a))g("improper JSON value in localStorage.nicknames");return a}function va(a){if(a===j||!ja(a))g("improper object for setting nicknames");window.localStorage.setItem("nicknames",window.JSON.stringify(a));window.localStorage.setItem("dirty","true")}
function wa(a){var b=ua();b[a]=j;va(b)}function xa(a){var b=ua();delete b[a];va(b)};function ya(a){for(var b=1;b<arguments.length;b++){var c=String(arguments[b]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,c)}return a}function za(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function Aa(a,b){if(b)return a.replace(Ba,"&amp;").replace(Ca,"&lt;").replace(Da,"&gt;").replace(Ea,"&quot;");else{if(!Fa.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Ba,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Ca,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Da,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Ea,"&quot;");return a}}var Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/\"/g,Fa=/[&<>\"]/;function Ga(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}
function Ha(a,b){for(var c=0,d=za(String(a)).split("."),e=za(String(b)).split("."),f=Math.max(d.length,e.length),h=0;c==0&&h<f;h++){var k=d[h]||"",m=e[h]||"",o=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var n=o.exec(k)||["","",""],u=w.exec(m)||["","",""];if(n[0].length==0&&u[0].length==0)break;c=Ia(n[1].length==0?0:parseInt(n[1],10),u[1].length==0?0:parseInt(u[1],10))||Ia(n[2].length==0,u[2].length==0)||Ia(n[2],u[2])}while(c==0)}return c}
function Ia(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var Ja,Ka,La,Ma,Na,Oa;function Pa(){return r.navigator?r.navigator.userAgent:j}function Qa(){return r.navigator}Na=Ma=La=Ka=Ja=l;var Ra;if(Ra=Pa()){var Sa=Qa();Ja=Ra.indexOf("Opera")==0;Ka=!Ja&&Ra.indexOf("MSIE")!=-1;Ma=(La=!Ja&&Ra.indexOf("WebKit")!=-1)&&Ra.indexOf("Mobile")!=-1;Na=!Ja&&!La&&Sa.product=="Gecko"}var Ta=Ja,x=Ka,y=Na,z=La,Ua=Ma,Va=Qa();Oa=(Va&&Va.platform||"").indexOf("Mac")!=-1;var Wa=!!Qa()&&(Qa().appVersion||"").indexOf("X11")!=-1,Xa;
a:{var Ya="",Za;if(Ta&&r.opera){var $a=r.opera.version;Ya=typeof $a=="function"?$a():$a}else{if(y)Za=/rv\:([^\);]+)(\)|;)/;else if(x)Za=/MSIE\s+([^\);]+)(\)|;)/;else if(z)Za=/WebKit\/(\S+)/;if(Za){var ab=Za.exec(Pa());Ya=ab?ab[1]:""}}if(x){var bb,cb=r.document;bb=cb?cb.documentMode:undefined;if(bb>parseFloat(Ya)){Xa=String(bb);break a}}Xa=Ya}var db={};function A(a){return db[a]||(db[a]=Ha(Xa,a)>=0)};function eb(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function gb(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function hb(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function ib(a,b){var c;if(c=b in a)delete a[b];return c}function jb(a,b,c){if(b in a)g(Error('The object already contains the key "'+b+'"'));a[b]=c}function kb(a){var b={},c;for(c in a)b[a[c]]=c;return b}var lb=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function mb(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<lb.length;e++){b=lb[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}}function nb(){var a=arguments.length;if(a==1&&s(arguments[0]))return nb.apply(j,arguments[0]);if(a%2)g(Error("Uneven number of arguments"));for(var b={},c=0;c<a;c+=2)b[arguments[c]]=arguments[c+1];return b};function ob(a){this.stack=Error().stack||"";if(a)this.message=String(a)}v(ob,Error);ob.prototype.name="CustomError";function pb(a,b){b.unshift(a);ob.call(this,ya.apply(j,b));b.shift();this.Bf=a}v(pb,ob);pb.prototype.name="AssertionError";function qb(a,b){if(!a){var c=Array.prototype.slice.call(arguments,2),d="Assertion failed";if(b){d+=": "+b;var e=c}g(new pb(""+d,e||[]))}return a};var B=Array.prototype,rb=B.indexOf?function(a,b,c){qb(a.length!=j);return B.indexOf.call(a,b,c)}:function(a,b,c){c=c==j?0:c<0?Math.max(0,a.length+c):c;if(t(a)){if(!t(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sb=B.forEach?function(a,b,c){qb(a.length!=j);B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},tb=B.filter?function(a,b,c){qb(a.length!=j);return B.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var m=h[k];if(b.call(c,m,k,a))e[f++]=m}return e},ub=B.map?function(a,b,c){qb(a.length!=j);return B.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)if(h in f)e[h]=b.call(c,f[h],h,a);return e},vb=B.every?function(a,b,c){qb(a.length!=j);return B.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return l;
return i};function wb(a,b){return rb(a,b)>=0}function xb(a,b){var c=rb(a,b),d;if(d=c>=0){qb(a.length!=j);B.splice.call(a,c,1)}return d}function yb(){return B.concat.apply(B,arguments)}function zb(a){if(s(a))return yb(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function Ab(a){qb(a.length!=j);return B.splice.apply(a,Bb(arguments,1))}function Bb(a,b,c){qb(a.length!=j);return arguments.length<=2?B.slice.call(a,b):B.slice.call(a,b,c)};var Cb;var Db=!x||A("9"),Eb=x&&!A("8");function Fb(){}Fb.prototype.gc=l;Fb.prototype.i=function(){if(!this.gc){this.gc=i;this.f()}};Fb.prototype.f=aa();function C(a,b){this.type=a;this.currentTarget=this.target=b}v(C,Fb);q=C.prototype;q.f=function(){delete this.type;delete this.target;delete this.currentTarget};q.Oa=l;q.lb=i;q.stopPropagation=function(){this.Oa=i};q.preventDefault=function(){this.lb=l};function Gb(a){a.preventDefault()};var Hb=new Function("a","return a");function Ib(a,b){a&&this.xa(a,b)}v(Ib,C);var Jb=[1,4,2];q=Ib.prototype;q.target=j;q.relatedTarget=j;q.offsetX=0;q.offsetY=0;q.clientX=0;q.clientY=0;q.screenX=0;q.screenY=0;q.button=0;q.keyCode=0;q.charCode=0;q.ctrlKey=l;q.altKey=l;q.shiftKey=l;q.metaKey=l;q.Ye=l;q.ja=j;
q.xa=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(y)try{Hb(d.nodeName)}catch(e){d=j}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Ye=Oa?a.metaKey:a.ctrlKey;this.state=a.state;this.ja=a;delete this.lb;delete this.Oa};function Kb(a,b){return Db?a.ja.button==b:a.type=="click"?b==0:!!(a.ja.button&Jb[b])}
q.stopPropagation=function(){Ib.c.stopPropagation.call(this);if(this.ja.stopPropagation)this.ja.stopPropagation();else this.ja.cancelBubble=i};q.preventDefault=function(){Ib.c.preventDefault.call(this);var a=this.ja;if(a.preventDefault)a.preventDefault();else{a.returnValue=l;if(Eb)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};q.f=function(){Ib.c.f.call(this);this.relatedTarget=this.currentTarget=this.target=this.ja=j};function Lb(){}var Mb=0;q=Lb.prototype;q.key=0;q.$a=l;q.Yc=l;q.xa=function(a,b,c,d,e,f){if(ia(a))this.od=i;else if(a&&a.handleEvent&&ia(a.handleEvent))this.od=l;else g(Error("Invalid listener argument"));this.Wa=a;this.Id=b;this.src=c;this.type=d;this.capture=!!e;this.Hb=f;this.Yc=l;this.key=++Mb;this.$a=l};q.handleEvent=function(a){if(this.od)return this.Wa.call(this.Hb||this.src,a);return this.Wa.handleEvent.call(this.Wa,a)};var Nb;var Ob=(Nb="ScriptEngine"in r&&r.ScriptEngine()=="JScript")?r.ScriptEngineMajorVersion()+"."+r.ScriptEngineMinorVersion()+"."+r.ScriptEngineBuildVersion():"0";function D(a,b){this.wd=b;this.Ia=[];if(a>this.wd)g(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var c=0;c<a;c++)this.Ia.push(this.bb())}v(D,Fb);q=D.prototype;q.Fa=j;q.bd=j;function Pb(a){if(a.Ia.length)return a.Ia.pop();return a.bb()}function Qb(a,b){a.Ia.length<a.wd?a.Ia.push(b):a.fc(b)}q.bb=function(){return this.Fa?this.Fa():{}};q.fc=function(a){if(this.bd)this.bd(a);else if(ja(a))if(ia(a.i))a.i();else for(var b in a)delete a[b]};
q.f=function(){D.c.f.call(this);for(var a=this.Ia;a.length;)this.fc(a.pop());delete this.Ia};var Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac;
(function(){function a(){return{I:0,ea:0}}function b(){return[]}function c(){function u(K){return h.call(u.src,u.key,K)}return u}function d(){return new Lb}function e(){return new Ib}var f=Nb&&!(Ha(Ob,"5.7")>=0),h;Wb=function(u){h=u};if(f){Rb=function(){return Pb(k)};Sb=function(u){Qb(k,u)};Tb=function(){return Pb(m)};Ub=function(u){Qb(m,u)};Vb=function(){return Pb(o)};Xb=function(){Qb(o,c())};Yb=function(){return Pb(w)};Zb=function(u){Qb(w,u)};$b=function(){return Pb(n)};ac=function(u){Qb(n,u)};
var k=new D(0,600);k.Fa=a;var m=new D(0,600);m.Fa=b;var o=new D(0,600);o.Fa=c;var w=new D(0,600);w.Fa=d;var n=new D(0,600);n.Fa=e}else{Rb=a;Sb=ea;Tb=b;Ub=ea;Vb=c;Xb=ea;Yb=d;Zb=ea;$b=e;ac=ea}})();var bc={},E={},cc={},dc={};
function F(a,b,c,d,e){if(b)if(s(b)){for(var f=0;f<b.length;f++)F(a,b[f],c,d,e);return j}else{d=!!d;var h=E;b in h||(h[b]=Rb());h=h[b];if(!(d in h)){h[d]=Rb();h.I++}h=h[d];var k=ka(a),m;h.ea++;if(h[k]){m=h[k];for(f=0;f<m.length;f++){h=m[f];if(h.Wa==c&&h.Hb==e){if(h.$a)break;return m[f].key}}}else{m=h[k]=Tb();h.I++}f=Vb();f.src=a;h=Yb();h.xa(c,f,a,b,d,e);c=h.key;f.key=c;m.push(h);bc[c]=h;cc[k]||(cc[k]=Tb());cc[k].push(h);if(a.addEventListener){if(a==r||!a.ad)a.addEventListener(b,f,d)}else a.attachEvent(ec(b),
f);return c}else g(Error("Invalid event type"))}function G(a,b,c,d,e){if(s(b)){for(var f=0;f<b.length;f++)G(a,b[f],c,d,e);return j}d=!!d;a=fc(a,b,d);if(!a)return l;for(f=0;f<a.length;f++)if(a[f].Wa==c&&a[f].capture==d&&a[f].Hb==e)return H(a[f].key);return l}
function H(a){if(!bc[a])return l;var b=bc[a];if(b.$a)return l;var c=b.src,d=b.type,e=b.Id,f=b.capture;if(c.removeEventListener){if(c==r||!c.ad)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(ec(d),e);c=ka(c);e=E[d][f][c];if(cc[c]){var h=cc[c];xb(h,b);h.length==0&&delete cc[c]}b.$a=i;e.zd=i;gc(d,f,c,e);delete bc[a];return i}
function gc(a,b,c,d){if(!d.Mb)if(d.zd){for(var e=0,f=0;e<d.length;e++)if(d[e].$a){var h=d[e].Id;h.src=j;Xb(h);Zb(d[e])}else{if(e!=f)d[f]=d[e];f++}d.length=f;d.zd=l;if(f==0){Ub(d);delete E[a][b][c];E[a][b].I--;if(E[a][b].I==0){Sb(E[a][b]);delete E[a][b];E[a].I--}if(E[a].I==0){Sb(E[a]);delete E[a]}}}}
function hc(a,b,c){var d=0,e=b==j,f=c==j;c=!!c;if(a==j)eb(cc,function(m){for(var o=m.length-1;o>=0;o--){var w=m[o];if((e||b==w.type)&&(f||c==w.capture)){H(w.key);d++}}});else{a=ka(a);if(cc[a]){a=cc[a];for(var h=a.length-1;h>=0;h--){var k=a[h];if((e||b==k.type)&&(f||c==k.capture)){H(k.key);d++}}}}return d}function fc(a,b,c){var d=E;if(b in d){d=d[b];if(c in d){d=d[c];a=ka(a);if(d[a])return d[a]}}return j}function ec(a){if(a in dc)return dc[a];return dc[a]="on"+a}
function ic(a,b,c,d,e){var f=1;b=ka(b);if(a[b]){a.ea--;a=a[b];if(a.Mb)a.Mb++;else a.Mb=1;try{for(var h=a.length,k=0;k<h;k++){var m=a[k];if(m&&!m.$a)f&=jc(m,e)!==l}}finally{a.Mb--;gc(c,d,b,a)}}return Boolean(f)}function jc(a,b){var c=a.handleEvent(b);a.Yc&&H(a.key);return c}
Wb(function(a,b){if(!bc[a])return i;var c=bc[a],d=c.type,e=E;if(!(d in e))return i;e=e[d];var f,h;if(Cb===undefined)Cb=x&&!r.addEventListener;if(Cb){var k;if(!(k=b))a:{k="window.event".split(".");for(var m=r;f=k.shift();)if(m[f]!=j)m=m[f];else{k=j;break a}k=m}f=k;k=i in e;m=l in e;if(k){if(f.keyCode<0||f.returnValue!=undefined)return i;a:{var o=l;if(f.keyCode==0)try{f.keyCode=-1;break a}catch(w){o=i}if(o||f.returnValue==undefined)f.returnValue=i}}o=$b();o.xa(f,this);f=i;try{if(k){for(var n=Tb(),u=
o.currentTarget;u;u=u.parentNode)n.push(u);h=e[i];h.ea=h.I;for(var K=n.length-1;!o.Oa&&K>=0&&h.ea;K--){o.currentTarget=n[K];f&=ic(h,n[K],d,i,o)}if(m){h=e[l];h.ea=h.I;for(K=0;!o.Oa&&K<n.length&&h.ea;K++){o.currentTarget=n[K];f&=ic(h,n[K],d,l,o)}}}else f=jc(c,o)}finally{if(n){n.length=0;Ub(n)}o.i();ac(o)}return f}d=new Ib(b,this);try{f=jc(c,d)}finally{d.i()}return f});function I(){}v(I,Fb);q=I.prototype;q.ad=i;q.Ob=j;q.Lc=ba("Ob");q.addEventListener=function(a,b,c,d){F(this,a,b,c,d)};q.removeEventListener=function(a,b,c,d){G(this,a,b,c,d)};
q.dispatchEvent=function(a){a=a;if(t(a))a=new C(a,this);else if(a instanceof C)a.target=a.target||this;else{var b=a;a=new C(a.type,this);mb(a,b)}b=1;var c,d=a.type,e=E;if(d in e){e=e[d];d=i in e;var f;if(d){c=[];for(f=this;f;f=f.Ob)c.push(f);f=e[i];f.ea=f.I;for(var h=c.length-1;!a.Oa&&h>=0&&f.ea;h--){a.currentTarget=c[h];b&=ic(f,c[h],a.type,i,a)&&a.lb!=l}}if(l in e){f=e[l];f.ea=f.I;if(d)for(h=0;!a.Oa&&h<c.length&&f.ea;h++){a.currentTarget=c[h];b&=ic(f,c[h],a.type,l,a)&&a.lb!=l}else for(c=this;!a.Oa&&
c&&f.ea;c=c.Ob){a.currentTarget=c;b&=ic(f,c,a.type,l,a)&&a.lb!=l}}a=Boolean(b)}else a=i;return a};q.f=function(){I.c.f.call(this);hc(this);this.Ob=j};function kc(a,b,c){this.vd=a;this.Sb=c;this.d=b;F(b,[lc,mc,nc,oc],this);this.ha=j;this.o=[];this.M=-1;this.O=0;this.Ga=this.h=j}v(kc,I);q=kc.prototype;q.Pe=10;q.de=i;q.Xc=l;q.be=l;q.sf=l;var lc="hilite",mc="select",oc="dismiss",nc="canceldismiss";q=kc.prototype;q.handleEvent=function(a){if(a.target==this.d)switch(a.type){case lc:this.da(a.Pb);break;case mc:pc(this);break;case nc:qc(this);break;case oc:rc(this)}};q.La=function(){return this.d.g};
function sc(a){var b=a.O+a.o.length-1;if(a.M>=a.O&&a.M<b){a.da(a.M+1);return i}else if(a.M==-1){a.da(a.O);return i}else if(a.M==b)if(a.Xc){a.da(-1);return l}else if(a.be){a.da(a.O);return i}return l}function tc(a){if(a.M>a.O){a.da(a.M-1);return i}else if(a.Xc&&a.M==a.O){a.da(-1);return l}else if(a.be&&(a.M==-1||a.M==a.O)){a.da(a.O+a.o.length-1);return i}return l}q.da=function(a){this.M=a;this.d.da(a);return uc(this,a)!=-1};
function pc(a){var b=uc(a,a.M);if(b!=-1){b=a.o[b];var c=a.Sb,d=b.toString();if(c.Za){var e=vc(c,c.k.value,wc(c.k)),f=xc(c,c.k.value);d=d;c.df.test(d)||(d=d.replace(/[\s\xa0]+$/,"")+c.je);if(c.wf){if(e!=0&&!/^[\s\xa0]*$/.test(f[e-1]))d=" "+d;if(e==f.length-1)d+=" "}if(d!=f[e]){f[e]=d;d=c.k;y&&d.blur();d.value=f.join("");for(var h=0,k=0;k<=e;k++)h+=f[k].length;d.focus();e=h;f=c.k;d=e;if(yc(f))f.selectionStart=d;else if(x){h=zc(f);k=h[0];if(k.inRange(h[1])){d=Ac(f,d);k.collapse(i);k.move("character",
d);k.select()}}f=c.k;e=e;if(yc(f))f.selectionEnd=e;else if(x){h=zc(f);d=h[1];if(h[0].inRange(d)){e=Ac(f,e);f=Ac(f,wc(f));d.collapse(i);d.moveEnd("character",e-f);d.select()}}}}else c.k.value=d;c.Ic=i;a.pa();a.dispatchEvent({type:"update",Pb:b});a.sf&&a.Sb.update(i);return i}else{a.pa();a.dispatchEvent({type:"update",Pb:j});return l}}q.pa=function(){this.M=-1;this.ha=j;this.O+=this.o.length;this.o=[];window.clearTimeout(this.Ga);this.Ga=j;this.d.pa()};
function rc(a){if(!a.Ga)a.Ga=window.setTimeout(pa(a.pa,a),100)}function qc(a){window.setTimeout(pa(function(){if(this.Ga){window.clearTimeout(this.Ga);this.Ga=j}},a),10)}q.f=function(){kc.c.f.call(this);this.d.i();this.Sb.i();this.vd=j};q.Oe=function(a,b,c){this.ha==a&&this.Fc(b,c)};
q.Fc=function(a,b){var c=b?uc(this,this.M):j;this.O+=this.o.length;this.o=a;for(var d=[],e=0;e<a.length;++e)d.push({id:this.O+e,data:a[e]});this.d.Fc(d,this.ha,this.h);if(this.de&&d.length!=0&&this.ha)this.da(c!=j?this.O+c:this.O);else this.M=-1};function uc(a,b){var c=b-a.O;if(c<0||c>=a.o.length)return-1;return c}q.$b=function(){var a=this.Sb;a.$b.apply(a,arguments)};function Bc(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}Bc.prototype.ab=function(){return new Bc(this.x,this.y)};Bc.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function J(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}J.prototype.ab=function(){return new J(this.top,this.right,this.bottom,this.left)};J.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};J.prototype.contains=function(a){a=!this||!a?l:a instanceof J?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom;return a};function L(a,b){this.width=a;this.height=b}L.prototype.ab=function(){return new L(this.width,this.height)};L.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};L.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};L.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Cc(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}Cc.prototype.ab=function(){return new Cc(this.left,this.top,this.width,this.height)};Cc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
Cc.prototype.contains=function(a){return a instanceof Cc?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};var Dc;function Ec(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function M(a){var b=Ec(a),c;c=Bb(arguments,1);for(var d=0,e=0;e<c.length;e++)if(!wb(b,c[e])){b.push(c[e]);d++}c=d==c.length;a.className=b.join(" ");return c}function Fc(a){var b=Ec(a),c;c=Bb(arguments,1);for(var d=0,e=0;e<b.length;e++)if(wb(c,b[e])){Ab(b,e--,1);d++}c=d==c.length;a.className=b.join(" ");return c};var Gc=!x||A("9"),Hc=x&&!A("9");function N(a){return a?new Ic(O(a)):Dc||(Dc=new Ic)}function P(a){return t(a)?document.getElementById(a):a}
function Jc(a,b,c,d){a=d||a;b=b&&b!="*"?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(!z||Kc(document)||A("528"))&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)if(b==h.nodeName)d[e++]=h;d.length=e;return d}else return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++){b=h.className;if(typeof b.split=="function"&&wb(b.split(/\s+/),c))d[e++]=h}d.length=e;return d}else return a}
function Lc(a,b){eb(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in Mc)a.setAttribute(Mc[d],c);else a[d]=c})}var Mc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function Nc(a){var b=a.document;if(z&&!A("500")&&!Ua){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new L(a.innerWidth,b)}a=Kc(b);if(Ta&&!A("9.50"))a=l;a=a?b.documentElement:b.body;return new L(a.clientWidth,a.clientHeight)}function Oc(){return Pc(document,arguments)}
function Pc(a,b){var c=b[0],d=b[1];if(!Gc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',Aa(d.name),'"');if(d.type){c.push(' type="',Aa(d.type),'"');var e={};mb(e,d);d=e;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(t(d))c.className=d;else s(d)?M.apply(j,[c].concat(d)):Lc(c,d);b.length>2&&Qc(a,c,b,2);return c}
function Qc(a,b,c,d){function e(h){if(h)b.appendChild(t(h)?a.createTextNode(h):h)}for(d=d;d<c.length;d++){var f=c[d];ha(f)&&!(ja(f)&&f.nodeType>0)?sb(Rc(f)?zb(f):f,e):e(f)}}function Kc(a){return a.compatMode=="CSS1Compat"}function Sc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Tc(a){return a&&a.parentNode?a.parentNode.removeChild(a):j}function Uc(a){for(a=a.firstChild;a&&a.nodeType!=1;)a=a.nextSibling;return a}
function Vc(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function O(a){return a.nodeType==9?a:a.ownerDocument||a.document}
function Wc(a,b){if("textContent"in a)a.textContent=b;else if(a.firstChild&&a.firstChild.nodeType==3){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{Sc(a);a.appendChild(O(a).createTextNode(b))}}var Xc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Yc={IMG:" ",BR:"\n"};function Zc(a){var b=a.getAttributeNode("tabindex");if(b&&b.specified){a=a.tabIndex;return typeof a=="number"&&a>=0}return l}
function $c(a){if(Hc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];ad(a,b,i);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");x||(a=a.replace(/ +/g," "));if(a!=" ")a=a.replace(/^\s*/,"");return a}function ad(a,b,c){if(!(a.nodeName in Xc))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Yc)b.push(Yc[a.nodeName]);else for(a=a.firstChild;a;){ad(a,b,c);a=a.nextSibling}}
function Rc(a){if(a&&typeof a.length=="number")if(ja(a))return typeof a.item=="function"||typeof a.item=="string";else if(ia(a))return typeof a.item=="function";return l}function Ic(a){this.u=a||r.document||document}q=Ic.prototype;q.m=N;function bd(a){return a.u}q.b=function(a){return t(a)?this.u.getElementById(a):a};q.e=function(){return Pc(this.u,arguments)};q.createElement=function(a){return this.u.createElement(a)};q.createTextNode=function(a){return this.u.createTextNode(a)};
function cd(a){a=!z&&Kc(a.u)?a.u.documentElement:a.u.body;return new Bc(a.scrollLeft,a.scrollTop)}q.appendChild=function(a,b){a.appendChild(b)};q.Jd=Sc;q.removeNode=Tc;q.contains=Vc;function dd(a,b){var c=O(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,j))return c[b]||c.getPropertyValue(b);return""}function ed(a,b){return dd(a,b)||(a.currentStyle?a.currentStyle[b]:j)||a.style[b]}function fd(a,b,c){var d,e=y&&(Oa||Wa)&&A("1.9");if(b instanceof Bc){d=b.x;b=b.y}else{d=b;b=c}a.style.left=gd(d,e);a.style.top=gd(b,e)}
function hd(a){a=a?a.nodeType==9?a:O(a):document;var b;if(b=x){b=N(a);b=!Kc(b.u)}if(b)return a.body;return a.documentElement}function id(a){if(x)return a.offsetParent;var b=O(a),c=ed(a,"position"),d=c=="fixed"||c=="absolute";for(a=a.parentNode;a&&a!=b;a=a.parentNode){c=ed(a,"position");d=d&&c=="static"&&a!=b.documentElement&&a!=b.body;if(!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||c=="fixed"||c=="absolute"))return a}return j}
function jd(a){var b,c=O(a),d=ed(a,"position"),e=y&&c.getBoxObjectFor&&!a.getBoundingClientRect&&d=="absolute"&&(b=c.getBoxObjectFor(a))&&(b.screenX<0||b.screenY<0),f=new Bc(0,0),h=hd(c);if(a==h)return f;if(a.getBoundingClientRect){b=a.getBoundingClientRect();if(x){a=a.ownerDocument;b.left-=a.documentElement.clientLeft+a.body.clientLeft;b.top-=a.documentElement.clientTop+a.body.clientTop}b=b;c=cd(N(c));f.x=b.left+c.x;f.y=b.top+c.y}else if(c.getBoxObjectFor&&!e){b=c.getBoxObjectFor(a);c=c.getBoxObjectFor(h);
f.x=b.screenX-c.screenX;f.y=b.screenY-c.screenY}else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;if(b!=a){f.x+=b.clientLeft||0;f.y+=b.clientTop||0}if(z&&ed(b,"position")=="fixed"){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ta||z&&d=="absolute")f.y-=c.body.offsetTop;for(b=a;(b=id(b))&&b!=c.body&&b!=h;){f.x-=b.scrollLeft;if(!Ta||b.tagName!="TR")f.y-=b.scrollTop}}return f}
function kd(a,b,c){if(b instanceof L){c=b.height;b=b.width}else{if(c==undefined)g(Error("missing height argument"));c=c}a.style.width=gd(b,i);a.style.height=gd(c,i)}function gd(a,b){if(typeof a=="number")a=(b?Math.round(a):a)+"px";return a}
function ld(a){var b=Ta&&!A("10");if(ed(a,"display")!="none")return b?new L(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new L(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=f;c.visibility=e;return new L(b,a)}
function md(a,b){var c=a.style;if("opacity"in c)c.opacity=b;else if("MozOpacity"in c)c.MozOpacity=b;else if("filter"in c)c.filter=b===""?"":"alpha(opacity="+b*100+")"}function Q(a,b){a.style.display=b?"":"none"}var nd=y?"MozUserSelect":z?"WebkitUserSelect":j;
function od(a,b,c){c=!c?a.getElementsByTagName("*"):j;if(nd){b=b?"none":"";a.style[nd]=b;if(c){a=0;for(var d;d=c[a];a++)d.style[nd]=b}}else if(x||Ta){b=b?"on":"";a.setAttribute("unselectable",b);if(c)for(a=0;d=c[a];a++)d.setAttribute("unselectable",b)}}var pd={thin:2,medium:4,thick:6};
function qd(a,b){if((a.currentStyle?a.currentStyle[b+"Style"]:j)=="none")return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:j;if(c in pd)return pd[c];var d;if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}return d};function rd(){}fa(rd);rd.prototype.Dc=0;function sd(a){return":"+(a.Dc++).toString(36)}rd.ka();var td="StopIteration"in r?r.StopIteration:Error("StopIteration");function ud(){}ud.prototype.next=function(){g(td)};ud.prototype.Xb=function(){return this};function vd(a){if(a instanceof ud)return a;if(typeof a.Xb=="function")return a.Xb(l);if(ha(a)){var b=0,c=new ud;c.next=function(){for(;;){if(b>=a.length)g(td);if(b in a)return a[b++];else b++}};return c}g(Error("Not implemented"))}
function wd(a,b,c){if(ha(a))try{sb(a,b,c)}catch(d){if(d!==td)g(d)}else{a=vd(a);try{for(;;)b.call(c,a.next(),undefined,a)}catch(e){if(e!==td)g(e)}}}function xd(a,b,c){a=vd(a);try{for(;;)if(b.call(c,a.next(),undefined,a))return i}catch(d){if(d!==td)g(d)}return l};function yd(a,b){if(y){a.setAttribute("role",b);a.Df=b}}function zd(a,b,c){y&&a.setAttribute("aria-"+b,c)};function Ad(a,b,c,d){this.l=a||document.body;this.q=N(this.l);this.af=!a;this.a=j;this.ha="";this.o=[];this.Od=this.Ib=-1;this.g=l;this.className="ac-renderer";this.Hc="ac-row";this.rd="active";this.Uc="ac-active";this.Ie="ac-highlighted";this.Ra=b||j;this.vf=d!=j?d:i;this.rc=l;this.cf=c!=j?c:l;this.xc=j;this.Wb=l}v(Ad,I);q=Ad.prototype;q.b=ca("a");q.Fc=function(a,b,c){this.ha=b;this.o=a;this.Ib=-1;this.Od=ra();this.h=c;this.nb=[];Bd(this)};
q.pa=function(){this.h&&zd(this.h,"activedescendant","");if(this.g){this.g=l;Q(this.a,l)}};q.show=function(){if(!this.g){this.g=i;Q(this.a,i)}};
function Cd(a,b){a.Ib>=0&&Fc(a.nb[a.Ib],a.Uc,a.rd);a.Ib=b;if(b>=0&&b<a.a.childNodes.length){var c=a.nb[b];M(c,a.Uc,a.rd);if(a.h)zd(a.h,"activedescendant",c?c.id:"");var d=a.a,e=jd(c),f=jd(d),h;if(x){var k=qd(d,"borderLeft");h=qd(d,"borderRight");var m=qd(d,"borderTop"),o=qd(d,"borderBottom");h=new J(m,h,o,k)}else{k=dd(d,"borderLeftWidth");h=dd(d,"borderRightWidth");m=dd(d,"borderTopWidth");o=dd(d,"borderBottomWidth");h=new J(parseFloat(m),parseFloat(h),parseFloat(o),parseFloat(k))}k=e.x-f.x-h.left;
e=e.y-f.y-h.top;f=d.clientHeight-c.offsetHeight;d.scrollLeft+=Math.min(k,Math.max(k-(d.clientWidth-c.offsetWidth),0));d.scrollTop+=Math.min(e,Math.max(e-f,0))}}q.da=function(a){if(a==-1)Cd(this,-1);else for(var b=0;b<this.o.length;b++)if(this.o[b].id==a){Cd(this,b);break}};
function Dd(a){if(!a.a){var b=a.q.e("div",{style:"display:none"});a.a=b;M(b,a.className);yd(b,"listbox");b.id=sd(rd.ka());if(a.h){yd(a.h,"combobox");zd(a.h,"autocomplete","list");zd(a.h,"haspopup",i)}a.q.appendChild(a.l,b);F(b,"click",a.fd,l,a);F(b,"mousedown",a.jd,l,a);F(a.q.u,"click",a.hd,l,a);F(b,"mouseover",a.kd,l,a)}}
function Bd(a){Dd(a);if(a.Wb)a.a.style.visibility="hidden";a.nb.length=0;a.q.Jd(a.a);if(a.Ra&&a.Ra.ma)a.Ra.ma(a,a.a,a.o,a.ha);else{var b=j;wd(a.o,function(c){c=c;var d=this.ha,e=this.q.e("div",{className:this.Hc,id:sd(rd.ka())});yd(e,"option");if(this.Ra&&this.Ra.$e)this.Ra.$e(c,d,e);else e.innerHTML=Aa(c.data.toString());d&&this.vf&&Ed(this,e,d);M(e,this.Hc);this.nb.push(e);c=e;this.Wb?this.a.insertBefore(c,b):this.q.appendChild(this.a,c);b=c},a)}if(a.o.length==0)a.pa();else{a.show();Fd(a,a.a);a.Gc();
od(a.a,i)}}q.Gc=function(){if(this.h&&this.af){var a=jd(this.h),b=ld(this.h),c=ld(hd(this.h)),d=ld(this.a);a.y=this.Wb?a.y-d.height:a.y+b.height;if((this.cf||a.x+d.width>c.width)&&this.xc!="LEFT"){a.x=a.x+b.width-d.width;this.xc="RIGHT"}else this.xc="LEFT";b=this.a;a=a;c=void 0;d=jd(b);if(a instanceof Bc){c=a.y;a=a.x}fd(b,b.offsetLeft+(a-d.x),b.offsetTop+(c-d.y));if(this.Wb)this.a.style.visibility="visible"}};
q.f=function(){Ad.c.f.call(this);if(this.a){G(this.a,"click",this.fd,l,this);G(this.a,"mousedown",this.jd,l,this);G(this.q.u,"click",this.hd,l,this);G(this.a,"mouseover",this.kd,l,this);this.q.removeNode(this.a);this.a=j;this.g=l}delete this.l};function Fd(a,b){if(y&&Oa){b.style.width="";b.style.overflow="visible";b.style.width=b.offsetWidth;b.style.overflow="auto"}}
function Ed(a,b,c){if(b.nodeType==3){var d=j;if(s(c)&&c.length>1&&!a.rc)d=Bb(c,1);c=Gd(a,c);if(c.length!=0){var e=b.nodeValue,f=RegExp("(.*?)(^|\\W+)("+c+")","gi");c=[];for(var h=0,k=f.exec(e),m=0;k;){m++;c.push(k[1]);c.push(k[2]);c.push(k[3]);h=f.lastIndex;k=f.exec(e)}c.push(e.substring(h));if(c.length>1){d=!a.rc?1:m;for(e=0;e<d;e++){f=3*e;b.nodeValue=c[f]+c[f+1];h=a.q.createElement("b");h.className=a.Ie;a.q.appendChild(h,a.q.createTextNode(c[f+2]));h=b.parentNode.insertBefore(h,b.nextSibling);b.parentNode.insertBefore(a.q.createTextNode(""),
h.nextSibling);b=h.nextSibling}a=Bb(c,d*3);b.nodeValue=a.join("")}else d&&Ed(a,b,d)}}else for(b=b.firstChild;b;){d=b.nextSibling;Ed(a,b,c);b=d}}function Gd(a,b){var c="";if(!b)return c;if(a.rc)if(s(b)){c=tb(b,function(d){return!/^[\s\xa0]*$/.test(d==j?"":String(d))});c=ub(c,Ga);c=c.join("|")}else{c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"");c=Ga(c);c=c.replace(/ /g,"|")}else c=s(b)?b.length>0?Ga(b[0]):"":Ga(b);return c}
function Hd(a,b){for(;b&&b!=a.a&&!wb(Ec(b),a.Hc);)b=b.parentNode;return b?rb(a.nb,b):-1}q.fd=function(a){var b=Hd(this,a.target);b>=0&&this.dispatchEvent({type:mc,Pb:this.o[b].id});a.stopPropagation()};q.jd=function(a){this.dispatchEvent(nc);a.stopPropagation();a.preventDefault()};q.hd=function(){this.dispatchEvent(oc)};q.kd=function(a){a=Hd(this,a.target);if(a>=0)ra()-this.Od<300||this.dispatchEvent({type:lc,Pb:this.o[a].id})};function Id(a,b){this.Jb=a||1;this.wb=b||Jd;this.ac=pa(this.lf,this);this.Ac=ra()}v(Id,I);Id.prototype.enabled=l;var Jd=r.window;q=Id.prototype;q.C=j;q.lf=function(){if(this.enabled){var a=ra()-this.Ac;if(a>0&&a<this.Jb*0.8)this.C=this.wb.setTimeout(this.ac,this.Jb-a);else{this.dispatchEvent(Kd);if(this.enabled){this.C=this.wb.setTimeout(this.ac,this.Jb);this.Ac=ra()}}}};q.start=function(){this.enabled=i;if(!this.C){this.C=this.wb.setTimeout(this.ac,this.Jb);this.Ac=ra()}};
q.stop=function(){this.enabled=l;if(this.C){this.wb.clearTimeout(this.C);this.C=j}};q.f=function(){Id.c.f.call(this);this.stop();delete this.wb};var Kd="tick";function Ld(a,b,c){if(ia(a)){if(c)a=pa(a,c)}else if(a&&typeof a.handleEvent=="function")a=pa(a.handleEvent,a);else g(Error("Invalid listener argument"));return b>2147483647?-1:Jd.setTimeout(a,b||0)};function Md(a){this.ld=a}v(Md,Fb);var Nd=new D(0,100);function R(a,b,c,d,e,f){if(s(c))for(var h=0;h<c.length;h++)R(a,b,c[h],d,e,f);else{b=F(b,c,d||a,e||l,f||a.ld||a);if(a.j)a.j[b]=i;else if(a.Aa){a.j=Pb(Nd);a.j[a.Aa]=i;a.Aa=j;a.j[b]=i}else a.Aa=b}return a}
function S(a,b,c,d,e,f){if(a.Aa||a.j)if(s(c))for(var h=0;h<c.length;h++)S(a,b,c[h],d,e,f);else{a:{d=d||a;f=f||a.ld||a;e=!!e;if(b=fc(b,c,e))for(c=0;c<b.length;c++)if(b[c].Wa==d&&b[c].capture==e&&b[c].Hb==f){b=b[c];break a}b=j}if(b){b=b.key;H(b);if(a.j)ib(a.j,b);else if(a.Aa==b)a.Aa=j}}return a}Md.prototype.removeAll=function(){if(this.j){for(var a in this.j){H(a);delete this.j[a]}Qb(Nd,this.j);this.j=j}else this.Aa&&H(this.Aa)};Md.prototype.f=function(){Md.c.f.call(this);this.removeAll()};
Md.prototype.handleEvent=function(){g(Error("EventHandler.handleEvent not implemented"))};function wc(a){var b;a:{var c=0,d=0;if(yc(a)){c=a.selectionStart;d=-1}else if(x){var e=zc(a);b=e[0];e=e[1];if(b.inRange(e)){b.setEndPoint("EndToStart",e);if(a.type=="textarea"){e.duplicate();c=a=b.text;for(d=l;!d;)if(b.compareEndPoints("StartToEnd",b)==0)d=i;else{b.moveEnd("character",-1);if(b.text==a)c+="\r\n";else d=i}b=[c.length,-1];break a}c=b.text.length;d=-1}}b=[c,d]}return b[0]}
function zc(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();if(a.type=="textarea"){b=b.body.createTextRange();b.moveToElementText(a)}else b=a.createTextRange();return[b,c]}function Ac(a,b){if(a.type=="textarea")b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length;return b}function yc(a){try{return typeof a.selectionStart=="number"}catch(b){return l}};function Od(a,b,c,d,e){if(!x&&!(z&&A("525")))return i;if(Oa&&e)return Pd(a);if(e&&!d)return l;if(!c&&(b==17||b==18))return l;if(x&&d&&b==a)return l;switch(a){case 13:return i;case 27:return!z}return Pd(a)}
function Pd(a){if(a>=48&&a<=57)return i;if(a>=96&&a<=106)return i;if(a>=65&&a<=90)return i;if(z&&a==0)return i;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return i;default:return l}};function Qd(a,b){a&&Rd(this,a,b)}v(Qd,I);q=Qd.prototype;q.a=j;q.Kb=j;q.yc=j;q.Lb=j;q.Ba=-1;q.za=-1;
var Sd={"3":13,"12":144,"63232":38,"63233":40,"63234":37,"63235":39,"63236":112,"63237":113,"63238":114,"63239":115,"63240":116,"63241":117,"63242":118,"63243":119,"63244":120,"63245":121,"63246":122,"63247":123,"63248":44,"63272":46,"63273":36,"63275":35,"63276":33,"63277":34,"63289":144,"63302":45},Td={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Ud={61:187,
59:186},Vd=x||z&&A("525");q=Qd.prototype;q.ze=function(a){if(z&&(this.Ba==17&&!a.ctrlKey||this.Ba==18&&!a.altKey))this.za=this.Ba=-1;if(Vd&&!Od(a.keyCode,this.Ba,a.shiftKey,a.ctrlKey,a.altKey))this.handleEvent(a);else this.za=y&&a.keyCode in Ud?Ud[a.keyCode]:a.keyCode};q.Be=function(){this.za=this.Ba=-1};
q.handleEvent=function(a){var b=a.ja,c,d;if(x&&a.type=="keypress"){c=this.za;d=c!=13&&c!=27?b.keyCode:0}else if(z&&a.type=="keypress"){c=this.za;d=b.charCode>=0&&b.charCode<63232&&Pd(c)?b.charCode:0}else if(Ta){c=this.za;d=Pd(c)?b.keyCode:0}else{c=b.keyCode||this.za;d=b.charCode||0;if(Oa&&d==63&&!c)c=191}var e=c,f=b.keyIdentifier;if(c)if(c>=63232&&c in Sd)e=Sd[c];else{if(c==25&&a.shiftKey)e=9}else if(f&&f in Td)e=Td[f];a=e==this.Ba;this.Ba=e;b=new Wd(e,d,a,b);try{this.dispatchEvent(b)}finally{b.i()}};
q.b=ca("a");function Rd(a,b,c){a.Lb&&a.detach();a.a=b;a.Kb=F(a.a,"keypress",a,c);a.yc=F(a.a,"keydown",a.ze,c,a);a.Lb=F(a.a,"keyup",a.Be,c,a)}q.detach=function(){if(this.Kb){H(this.Kb);H(this.yc);H(this.Lb);this.Lb=this.yc=this.Kb=j}this.a=j;this.za=this.Ba=-1};q.f=function(){Qd.c.f.call(this);this.detach()};function Wd(a,b,c,d){d&&this.xa(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}v(Wd,Ib);function Xd(a,b,c,d){d=d||150;this.ob=a!=j?a:Yd;this.je=this.ob.substring(0,1);a=this.Za?"[\\s"+this.ob+"]+":"[\\s]+";this.Xd=RegExp("^"+a+"|"+a+"$","g");this.df=RegExp("\\s*["+this.ob+"]$");this.sd=b||"";this.Ze=this.Za=c!=j?c:i;this.C=d>0?new Id(d):j;this.K=new Md(this);this.xb=new Md(this);this.A=new Qd;this.qd=-1}v(Xd,Fb);var Yd=",;";q=Xd.prototype;q.wf=i;q.te=i;q.Yd=l;q.ff=i;q.ef=i;q.k=j;q.zc="";q.Ea=l;q.Ic=l;q.tf=i;
q.$b=function(){for(var a=0;a<arguments.length;a++){var b=arguments[a];zd(b,"haspopup",i);R(this.K,b,"focus",this.wa);R(this.K,b,"blur",this.Ja);this.k||R(this.xb,b,"keydown",this.Ue)}};q.f=function(){Xd.c.f.call(this);this.K.i();delete this.K;this.xb.i();this.xb=j};
q.la=function(a){switch(a.keyCode){case 40:if(this.p.La()){this.Yd?tc(this.p):sc(this.p);a.preventDefault();return i}else if(!this.Za){this.update(i);a.preventDefault();return i}break;case 38:if(this.p.La()){this.Yd?sc(this.p):tc(this.p);a.preventDefault();return i}break;case 9:if(this.p.La()&&!a.shiftKey){this.update();if(pc(this.p)&&this.Ze){a.preventDefault();return i}}else this.p.pa();break;case 13:if(this.p.La()){this.update();if(pc(this.p)){a.preventDefault();a.stopPropagation();return i}}else this.p.pa();
break;case 27:if(this.p.La()){this.p.pa();a.preventDefault();a.stopPropagation();return i}break;case 229:if(!this.Ea){if(!this.Ea){R(this.K,this.k,"keyup",this.Dd);R(this.K,this.k,"keypress",this.Cd);this.Ea=i}return i}break;default:if(this.C&&!this.tf){this.C.stop();this.C.start()}}return Zd(this,a)};function Zd(a,b){var c=a.Za&&b.charCode&&a.ob.indexOf(String.fromCharCode(b.charCode))!=-1;a.ff&&c&&a.update();if(a.ef&&c)if(pc(a.p)){b.preventDefault();return i}return l}q.Ae=p(l);
q.wa=function(a){this.xb.removeAll();this.p&&qc(this.p);if(a.target!=this.k){this.k=a.target||j;if(this.C){this.C.start();R(this.K,this.C,Kd,this.Gd)}this.zc=this.k.value;Rd(this.A,this.k);R(this.K,this.A,"key",this.Na);x&&R(this.K,this.k,"keypress",this.Bd)}};q.Ja=function(){if(this.k){S(this.K,this.A,"key",this.Na);this.A.detach();S(this.K,this.k,"keyup",this.Ae);x&&S(this.K,this.k,"keypress",this.Bd);this.Ea&&$d(this);this.k=j;if(this.C){this.C.stop();S(this.K,this.C,Kd,this.Gd)}this.p&&rc(this.p)}};
q.Gd=function(){this.update()};q.Ue=function(a){this.wa(a)};q.Na=function(a){this.qd=a.keyCode;this.p&&this.la(a)};q.Cd=function(){this.Ea&&this.qd!=229&&$d(this)};q.Dd=function(a){if(this.Ea&&(a.keyCode==13||a.keyCode==77&&a.ctrlKey))$d(this)};function $d(a){if(a.Ea){a.Ea=l;S(a.K,a.k,"keypress",a.Cd);S(a.K,a.k,"keyup",a.Dd)}}q.Bd=function(a){Zd(this,a)};
q.update=function(a){if(a||this.k&&this.k.value!=this.zc){if(a||!this.Ic){var b;a=wc(this.k);b=this.k.value;a=xc(this,b)[vc(this,b,a)];b=this.Xd?String(a).replace(this.Xd,""):a;if(this.p){this.p.h=this.k;a=this.p;if(a.ha!=b){a.ha=b;b=a.vd;var c=a.ha,d=a.Pe,e=pa(a.Oe,a),f=ae(b,c,d);if(f.length==0&&b.uf)f=be(b,c,d);e(c,f);qc(a)}}}this.zc=this.k.value}this.Ic=l};function vc(a,b,c){a=xc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<c;d++){e+=a[d].length;b=d}return b}
function xc(a,b){if(!a.Za)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,h=l;f<c.length;f++)if(a.sd&&a.sd.indexOf(c[f])!=-1){if(a.te&&!h){d.push(e.join(""));e.length=0}e.push(c[f]);h=!h}else if(!h&&a.ob.indexOf(c[f])!=-1){e.push(c[f]);d.push(e.join(""));e.length=0}else e.push(c[f]);d.push(e.join(""));return d};function ce(a,b){this.o=a;this.uf=!b}function ae(a,b,c){var d=[];if(b!=""){b=Ga(b);var e=RegExp("(^|\\W+)"+b,"i");xd(a.o,function(f){String(f).match(e)&&d.push(f);return d.length>=c})}return d}
function be(a,b,c){var d=[];wd(a.o,function(f,h){var k=b.toLowerCase(),m=String(f).toLowerCase(),o=0;if(m.indexOf(k)!=-1)o=parseInt((m.indexOf(k)/4).toString(),10);else for(var w=k.split(""),n=-1,u=10,K=0,fb;fb=w[K];K++){fb=m.indexOf(fb);if(fb>n){n=fb-n-1;if(n>u-5)n=u-5;o+=n;n=fb}else{o+=u;u+=5}}o<k.length*6&&d.push({jf:f,Md:o,index:h})});d.sort(function(f,h){var k=f.Md-h.Md;if(k!=0)return k;return f.index-h.index});a=[];for(var e=0;e<c&&e<d.length;e++)a.push(d[e].jf);return a};function de(a,b,c,d){a=new ce(a,!d);d=new Ad;c=new Xd(j,j,!!c);kc.call(this,a,d,c);c.p=this;c.$b(b)}v(de,kc);function ee(a){if(typeof a.Gb=="function")return a.Gb();if(t(a))return a.split("");if(ha(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return gb(a)}function fe(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(ha(a)||t(a))sb(a,b,c);else{var d;if(typeof a.Fb=="function")d=a.Fb();else if(typeof a.Gb!="function")if(ha(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f);d=d}else d=hb(a);else d=void 0;e=ee(a);f=e.length;for(var h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};function ge(a){this.Ma={};this.j=[];var b=arguments.length;if(b>1){if(b%2)g(Error("Uneven number of arguments"));for(var c=0;c<b;c+=2)this.set(arguments[c],arguments[c+1])}else if(a){if(a instanceof ge){b=a.Fb();c=a.Gb()}else{b=hb(a);c=gb(a)}for(var d=0;d<b.length;d++)this.set(b[d],c[d])}}q=ge.prototype;q.I=0;q.Tc=0;q.Gb=function(){he(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.Ma[this.j[b]]);return a};q.Fb=function(){he(this);return this.j.concat()};
function he(a){if(a.I!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];if(Object.prototype.hasOwnProperty.call(a.Ma,d))a.j[c++]=d;b++}a.j.length=c}if(a.I!=a.j.length){var e={};for(c=b=0;b<a.j.length;){d=a.j[b];if(!Object.prototype.hasOwnProperty.call(e,d)){a.j[c++]=d;e[d]=1}b++}a.j.length=c}}q.get=function(a,b){if(Object.prototype.hasOwnProperty.call(this.Ma,a))return this.Ma[a];return b};
q.set=function(a,b){if(!Object.prototype.hasOwnProperty.call(this.Ma,a)){this.I++;this.j.push(a);this.Tc++}this.Ma[a]=b};q.ab=function(){return new ge(this)};q.Xb=function(a){he(this);var b=0,c=this.j,d=this.Ma,e=this.Tc,f=this,h=new ud;h.next=function(){for(;;){if(e!=f.Tc)g(Error("The map has changed since the iterator was created"));if(b>=c.length)g(td);var k=c[b++];return a?k:d[k]}};return h};function ie(){this.ed=[];this.Hd=new ge;this.pf=this.qf=this.rf=this.gf=0;this.Sd=new ge;this.ie=this.of=0;this.Dc=1;this.re=new D(0,4E3);this.re.bb=function(){return new je};this.hf=new D(0,50);this.hf.bb=function(){return new ke};var a=this;this.nd=new D(0,2E3);this.nd.bb=function(){return String(a.Dc++)};this.nd.fc=aa();this.zf=3}function ke(){this.Zd=this.mf=this.$c=0}
ke.prototype.toString=function(){var a=[];a.push(this.type," ",this.$c," (",Math.round(this.mf*10)/10," ms)");this.Zd&&a.push(" [VarAlloc = ",this.Zd,"]");return a.join("")};function je(){}function le(a,b,c,d){var e=[];c==-1?e.push("    "):e.push(me(a.dd-c));e.push(" ",ne(a.dd-b));if(a.jc==0)e.push(" Start        ");else if(a.jc==1){e.push(" Done ");e.push(me(a.Ef-a.startTime)," ms ")}else e.push(" Comment      ");e.push(d,a);a.nf>0&&e.push("[VarAlloc ",a.nf,"] ");return e.join("")}
je.prototype.toString=function(){return this.type==j?this.he:"["+this.type+"] "+this.he};
ie.prototype.toString=function(){for(var a=[],b=-1,c=[],d=0;d<this.ed.length;d++){var e=this.ed[d];e.jc==1&&c.pop();a.push(" ",le(e,this.gf,b,c.join("")));b=e.dd;a.push("\n");e.jc==0&&c.push("|  ")}if(this.Hd.I!=0){var f=ra();a.push(" Unstopped timers:\n");wd(this.Hd,function(h){a.push("  ",h," (",f-h.startTime," ms, started at ",ne(h.startTime),")\n")})}b=this.Sd.Fb();for(d=0;d<b.length;d++){c=this.Sd.get(b[d]);c.$c>1&&a.push(" TOTAL ",c,"\n")}a.push("Total tracers created ",this.of,"\n","Total comments created ",
this.ie,"\n","Overhead start: ",this.rf," ms\n","Overhead end: ",this.qf," ms\n","Overhead comment: ",this.pf," ms\n");return a.join("")};function me(a){a=Math.round(a);var b="";if(a<1E3)b=" ";if(a<100)b="  ";if(a<10)b="   ";return b+a}function ne(a){a=Math.round(a);return String(100+a/1E3%60).substring(1,3)+"."+String(1E3+a%1E3).substring(1,4)}new ie;/*

 A JavaScript implementation of the RSA Data Security, Inc. MD5 Message
 Digest Algorithm, as defined in RFC 1321.
 Version 2.1 Copyright (C) Paul Johnston 1999 - 2002.
 Other contributors: Greg Holt, Andrew Kepert, Ydnar, Lostinet
 Distributed under the BSD License
 See http://pajhome.org.uk/crypt/md5 for more info.
*/
window.goog=window.goog||{};window.goog.Ec=window.goog.Ec||function(a){window[a]={}};function T(a,b,c,d,e,f){return oe(oe(oe(b,a),oe(d,f))<<e|oe(oe(b,a),oe(d,f))>>>32-e,c)}function U(a,b,c,d,e,f,h){return T(b&c|~b&d,a,b,e,f,h)}function V(a,b,c,d,e,f,h){return T(b&d|c&~d,a,b,e,f,h)}function W(a,b,c,d,e,f,h){return T(c^(b|~d),a,b,e,f,h)}function oe(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535};window.goog=window.goog||{};window.goog.Ec=window.goog.Ec||function(a){window[a]={}};window.goog.bf=window.goog.bf||aa();function pe(a){for(var b=[],c=0;c<a.length;c+=1){var d=a.charCodeAt(c);d<128?b.push(String.fromCharCode(d)):b.push(String.fromCharCode(192|d>>6,128|d&63))}return b.join("")};function qe(a){var b=P("newNickname");if(b)b.style.display="none";b=P("validateMasterPassword");b.style.display="inline";if(a===undefined||a)b.focus()}function re(){var a=P("isNewNickname");a&&F(a,"click",qe)};da("oplop.ui.extension.onLoad",function(){var a=ua(),b=[],c;for(c in a)b.push(c);new de(b,P("nickname"),l,l);F(P("masterPassword"),"focus",se);F(P("createAccountPassword"),"click",te);a=chrome.extension.getURL("options.html");b=P("optionsLink");b.href=a;if(window.localStorage.getItem("dirty")){b.style.color="red";b.innerText="Unsaved nicknames!"}var d=new XMLHttpRequest;d.onreadystatechange=function(){if(d.readyState===4){var e=window.JSON.parse(d.responseText).version,f=e.split(".");if(new Date-
new Date(f[0],f[1]-1,f[2])<6048E5){f=P("newReleaseItem");f.style.display="inline";f=Uc(f);f.href="http://code.google.com/p/oplop/wiki/ChromeExtensionReleaseNotes#"+e;f.innerText+=" ("+e+")"}}};d.open("GET",chrome.extension.getURL("manifest.json"),i);d.send();re()},void 0);function se(){P("nickname").value in ua()||qe(l)}
function te(){chrome.tabs.getSelected(j,function(a){var b=P("nickname").value,c;c=P("validateMasterPassword");var d=c.style.display;if(!d||d==="none"||P("masterPassword").value==c.value){c=P("nickname").value;d=pe(P("masterPassword").value);var e=pe(c),f=d+e;c=[];for(var h=0;h<f.length*8;h+=8)c[h>>5]|=(f.charCodeAt(h/8)&255)<<h%32;d=(d+e).length*8;c[d>>5]|=128<<d%32;c[(d+64>>>9<<4)+14]=d;d=1732584193;e=-271733879;f=-1732584194;h=271733878;for(var k=0;k<c.length;k+=16){var m=d,o=e,w=f,n=h;d=U(d,e,
f,h,c[k+0],7,-680876936);h=U(h,d,e,f,c[k+1],12,-389564586);f=U(f,h,d,e,c[k+2],17,606105819);e=U(e,f,h,d,c[k+3],22,-1044525330);d=U(d,e,f,h,c[k+4],7,-176418897);h=U(h,d,e,f,c[k+5],12,1200080426);f=U(f,h,d,e,c[k+6],17,-1473231341);e=U(e,f,h,d,c[k+7],22,-45705983);d=U(d,e,f,h,c[k+8],7,1770035416);h=U(h,d,e,f,c[k+9],12,-1958414417);f=U(f,h,d,e,c[k+10],17,-42063);e=U(e,f,h,d,c[k+11],22,-1990404162);d=U(d,e,f,h,c[k+12],7,1804603682);h=U(h,d,e,f,c[k+13],12,-40341101);f=U(f,h,d,e,c[k+14],17,-1502002290);
e=U(e,f,h,d,c[k+15],22,1236535329);d=V(d,e,f,h,c[k+1],5,-165796510);h=V(h,d,e,f,c[k+6],9,-1069501632);f=V(f,h,d,e,c[k+11],14,643717713);e=V(e,f,h,d,c[k+0],20,-373897302);d=V(d,e,f,h,c[k+5],5,-701558691);h=V(h,d,e,f,c[k+10],9,38016083);f=V(f,h,d,e,c[k+15],14,-660478335);e=V(e,f,h,d,c[k+4],20,-405537848);d=V(d,e,f,h,c[k+9],5,568446438);h=V(h,d,e,f,c[k+14],9,-1019803690);f=V(f,h,d,e,c[k+3],14,-187363961);e=V(e,f,h,d,c[k+8],20,1163531501);d=V(d,e,f,h,c[k+13],5,-1444681467);h=V(h,d,e,f,c[k+2],9,-51403784);
f=V(f,h,d,e,c[k+7],14,1735328473);e=V(e,f,h,d,c[k+12],20,-1926607734);d=T(e^f^h,d,e,c[k+5],4,-378558);h=T(d^e^f,h,d,c[k+8],11,-2022574463);f=T(h^d^e,f,h,c[k+11],16,1839030562);e=T(f^h^d,e,f,c[k+14],23,-35309556);d=T(e^f^h,d,e,c[k+1],4,-1530992060);h=T(d^e^f,h,d,c[k+4],11,1272893353);f=T(h^d^e,f,h,c[k+7],16,-155497632);e=T(f^h^d,e,f,c[k+10],23,-1094730640);d=T(e^f^h,d,e,c[k+13],4,681279174);h=T(d^e^f,h,d,c[k+0],11,-358537222);f=T(h^d^e,f,h,c[k+3],16,-722521979);e=T(f^h^d,e,f,c[k+6],23,76029189);d=
T(e^f^h,d,e,c[k+9],4,-640364487);h=T(d^e^f,h,d,c[k+12],11,-421815835);f=T(h^d^e,f,h,c[k+15],16,530742520);e=T(f^h^d,e,f,c[k+2],23,-995338651);d=W(d,e,f,h,c[k+0],6,-198630844);h=W(h,d,e,f,c[k+7],10,1126891415);f=W(f,h,d,e,c[k+14],15,-1416354905);e=W(e,f,h,d,c[k+5],21,-57434055);d=W(d,e,f,h,c[k+12],6,1700485571);h=W(h,d,e,f,c[k+3],10,-1894986606);f=W(f,h,d,e,c[k+10],15,-1051523);e=W(e,f,h,d,c[k+1],21,-2054922799);d=W(d,e,f,h,c[k+8],6,1873313359);h=W(h,d,e,f,c[k+15],10,-30611744);f=W(f,h,d,e,c[k+6],
15,-1560198380);e=W(e,f,h,d,c[k+13],21,1309151649);d=W(d,e,f,h,c[k+4],6,-145523070);h=W(h,d,e,f,c[k+11],10,-1120210379);f=W(f,h,d,e,c[k+2],15,718787259);e=W(e,f,h,d,c[k+9],21,-343485551);d=oe(d,m);e=oe(e,o);f=oe(f,w);h=oe(h,n)}c=[d,e,f,h];d="";for(e=0;e<c.length*4;e+=3){f=(c[e>>2]>>8*(e%4)&255)<<16|(c[e+1>>2]>>8*((e+1)%4)&255)<<8|c[e+2>>2]>>8*((e+2)%4)&255;for(h=0;h<4;h++)d+=e*8+h*6>c.length*32?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(f>>6*(3-h)&63)}c=d;d=/\d+/;
e=c.search(d);if(e<0)c="1"+c;else if(e>=8)c=c.match(d)+c;c=c.substring(0,8);d=Jc(document,"input",void 0,void 0);for(e=0;e<d.length;e+=1){f=d[e];if(f.type=="password"||f.type=="text")f.value=""}Uc(P("masterPasswordSection")).style.backgroundColor="PaleGreen";c=c}else{c=P("masterPasswordSection");d=P("masterPassword");P("validateMasterPassword").value="";Uc(c).style.backgroundColor="red";d.value="";d.focus();c=j}if(c!==j){if(chrome.extension.getBackgroundPage().passwordCount[a.id]<=2){chrome.tabs.sendRequest(a.id,
{accountPassword:c});window.close()}else{a=Oc("input",{id:"accountPassword",size:8,value:c,autocomplete:"off"});c=["nicknameSection","masterPasswordSection"];for(d=0;d<c.length;d+=1)P(c[d]).style.display="none";c=P("createAccountPassword");(d=c.parentNode)&&d.replaceChild(a,c);a.select()}b in ua()||wa(b)}})};function ue(a,b,c){this.target=a;this.handle=b||a;this.Bc=c||new Cc(NaN,NaN,NaN,NaN);this.u=O(a);this.ia=new Md(this);F(this.handle,"mousedown",this.tb,l,this)}v(ue,I);var ve=x||y&&A("1.9.3");q=ue.prototype;q.screenX=0;q.screenY=0;q.Pd=0;q.Qd=0;q.eb=0;q.fb=0;q.aa=i;q.va=l;q.md=0;q.Re=0;q.Ke=l;q.ca=ca("ia");q.Nd=ba("Qb");q.setEnabled=ba("aa");q.f=function(){ue.c.f.call(this);G(this.handle,"mousedown",this.tb,l,this);this.ia.i();delete this.target;delete this.handle;delete this.ia};
q.tb=function(a){if(this.aa&&!this.va&&(a.type!="mousedown"||Kb(a,0))){if(this.md==0){we(this,a);if(this.va)a.preventDefault();else return}else a.preventDefault();var b=this.u,c=b.documentElement,d=!ve;R(this.ia,b,"mousemove",this.Se,d);R(this.ia,b,"mouseup",this.Ha,d);if(ve){c.setCapture(l);R(this.ia,c,"losecapture",this.Ha)}else R(this.ia,b?b.parentWindow||b.defaultView:window,"blur",this.Ha);x&&this.Ke&&R(this.ia,b,"dragstart",Gb);this.Qb&&R(this.ia,this.Qb,"scroll",this.Ve,d);this.screenX=this.Pd=
a.screenX;this.screenY=this.Qd=a.screenY;this.eb=this.target.offsetLeft;this.fb=this.target.offsetTop;this.kb=cd(N(this.u));this.Re=ra()}};function we(a,b){if(a.dispatchEvent(new xe("start",a,b.clientX,b.clientY,b))!==l)a.va=i}q.Ha=function(a,b){this.ia.removeAll();ve&&this.u.releaseCapture();if(this.va){this.va=l;this.dispatchEvent(new xe("end",this,a.clientX,a.clientY,a,ye(this,this.eb),ze(this,this.fb),b))}};
q.Se=function(a){if(this.aa){var b=a.screenX-this.screenX,c=a.screenY-this.screenY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.va){var d=this.Pd-this.screenX,e=this.Qd-this.screenY;if(d*d+e*e>this.md){we(this,a);if(!this.va){this.Ha(a);return}}}c=Ae(this,b,c);b=c.x;c=c.y;if(this.va)if(this.dispatchEvent(new xe("beforedrag",this,a.clientX,a.clientY,a,b,c))!==l){Be(this,a,b,c,l);a.preventDefault()}}};
function Ae(a,b,c){var d=cd(N(a.u));b+=d.x-a.kb.x;c+=d.y-a.kb.y;a.kb=d;a.eb+=b;a.fb+=c;return new Bc(ye(a,a.eb),ze(a,a.fb))}q.Ve=function(a){var b=Ae(this,0,0);a.clientX=this.kb.x-this.screenX;a.clientY=this.kb.x-this.screenY;Be(this,a,b.x,b.y,i)};function Be(a,b,c,d){a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new xe("drag",a,b.clientX,b.clientY,b,c,d))}
function ye(a,b){var c=a.Bc,d=!isNaN(c.left)?c.left:j;c=!isNaN(c.width)?c.width:0;return Math.min(d!=j?d+c:Infinity,Math.max(d!=j?d:-Infinity,b))}function ze(a,b){var c=a.Bc,d=!isNaN(c.top)?c.top:j;c=!isNaN(c.height)?c.height:0;return Math.min(d!=j?d+c:Infinity,Math.max(d!=j?d:-Infinity,b))}function xe(a,b,c,d,e,f,h,k){C.call(this,a);this.clientX=c;this.clientY=d;this.xf=e;this.left=f!==undefined?f:b.eb;this.top=h!==undefined?h:b.fb;this.Af=b;this.le=!!k}v(xe,C);function Ce(){this.ya=[];this.Vd=[];this.Rb=[]}v(Ce,I);q=Ce.prototype;q.vc=l;q.wc=l;q.tc=l;q.Wc=function(){g(Error("Call to pure virtual method"))};function De(a,b){a.Vd.push(b);b.wc=i;a.vc=i}q.Nd=ba("Qb");q.xa=function(){if(!this.tc){for(var a,b=0;a=this.ya[b];b++)Ee(this,a);this.tc=i}};function Ee(a,b){if(a.vc){F(b.element,"mousedown",b.xd,l,b);a.Oc&&M(b.element,a.Oc)}a.wc&&a.Qc&&M(b.element,a.Qc)}
function Fe(a,b){if(a.vc){G(b.element,"mousedown",b.xd,l,b);a.Oc&&Fc(b.element,a.Oc)}a.wc&&a.Qc&&Fc(b.element,a.Qc)}
q.tb=function(a,b){if(!this.V){this.V=b;var c=new Ge("dragstart",this,this.V);if(this.dispatchEvent(c)==l){c.i();this.V=j}else{c.i();c=b.Qa;var d;a:{d=c.cloneNode(i);switch(c.tagName.toLowerCase()){case "tr":d=Oc("table",j,Oc("tbody",j,d));break a;case "td":case "th":d=Oc("table",j,Oc("tbody",j,Oc("tr",j,d)));break a;default:d=d}}this.me&&M(d,this.me);this.Sa=d;d=O(c);d.body.appendChild(this.Sa);var e=this.Sa,f=jd(c);f.x+=(parseInt(ed(c,"marginLeft"),10)||0)*2;f.y+=(parseInt(ed(c,"marginTop"),10)||
0)*2;e.style.position="absolute";e.style.left=f.x+"px";e.style.top=f.y+"px";this.J=new ue(e);this.J.Nd(this.Qb);F(this.J,"drag",this.yd,l,this);F(this.J,"end",this.Ha,l,this);F(d.body,"selectstart",this.Td);this.vb=[];for(d=0;c=this.Vd[d];d++){var h;for(e=0;h=c.ya[e];e++){f=c;h=h;for(var k=[h.element],m=this.vb,o=0;o<k.length;o++){var w=k[o],n=jd(w),u=ld(w);n=new J(n.y,n.x+u.width,n.y+u.height,n.x);m.push(new He(n,f,h,w));if(m.length==1)this.sa=new J(n.top,n.right,n.bottom,n.left);else{w=this.sa;
w.left=Math.min(n.left,w.left);w.right=Math.max(n.right,w.right);w.top=Math.min(n.top,w.top);w.bottom=Math.max(n.bottom,w.bottom)}}}}if(!this.sa)this.sa=new J(0,0,0,0);this.Pa=j;for(d=0;c=this.Rb[d];d++){F(c.a,"scroll",this.Zc,l,this);c.dc=[];c.Kd=c.a.scrollLeft;c.Ld=c.a.scrollTop;e=jd(c.a);f=ld(c.a);c.Q=new J(e.y,e.x+f.width,e.y+f.height,e.x)}for(d=0;f=this.vb[d];d++)for(e=0;c=this.Rb[e];e++)if(Vc(c.a,f.a)){c.dc.push(f);f.Jc=c}this.J.tb(a);a.preventDefault()}}};
q.Ha=function(a){var b=a.le?j:this.Pa;if(b&&b.h){var c=a.clientX;a=a.clientY;var d=cd(N(this.Sa)),e=c+d.x;d=a+d.y;var f;if(this.ub)f=this.ub(b.ra,b.Q,e,d);var h=new Ge("drag",this,this.V,b.h,b.ra,b.a,c,a,e,d);this.dispatchEvent(h);h.i();c=new Ge("drop",this,this.V,b.h,b.ra,b.a,c,a,e,d,f);b.h.dispatchEvent(c);c.i()}b=new Ge("dragend",this,this.V);this.dispatchEvent(b);b.i();G(this.J,"drag",this.yd,l,this);G(this.J,"end",this.Ha,l,this);G(O(this.V.Qa).body,"selectstart",this.Td);for(b=0;c=this.Rb[b];b++){G(c.a,
"scroll",this.Zc,l,this);c.dc=[]}this.J.i();Tc(this.Sa);delete this.V;delete this.Sa;delete this.J;delete this.vb;delete this.Pa};
q.yd=function(a){var b=a.clientX,c=a.clientY,d=cd(N(this.Sa));b+=d.x;c+=d.y;d=this.Pa;var e;if(d){if(this.ub&&d.h)e=this.ub(d.ra,d.Q,b,c);if(Ie(this,b,c,d.Q)&&e==this.Vc)return;if(d.h){var f=new Ge("dragout",this,this.V,d.h,d.ra,d.a);this.dispatchEvent(f);f.i();f=new Ge("dragout",this,this.V,d.h,d.ra,d.a,undefined,undefined,undefined,undefined,this.Vc);d.h.dispatchEvent(f);f.i()}this.Vc=e;this.Pa=j}if(Ie(this,b,c,this.sa)){a:{for(f=0;d=this.vb[f];f++)if(Ie(this,b,c,d.Q))if(d.Jc){if(Ie(this,b,c,d.Jc.Q)){d=
d;break a}}else{d=d;break a}d=j}if((d=this.Pa=d)&&d.h){if(this.ub)e=this.ub(d.ra,d.Q,b,c);c=new Ge("dragover",this,this.V,d.h,d.ra,d.a);c.kf=e;this.dispatchEvent(c);c.i();a=new Ge("dragover",this,this.V,d.h,d.ra,d.a,a.clientX,a.clientY,undefined,undefined,e);d.h.dispatchEvent(a);a.i()}else if(!d){a=b;c=c;if(!this.ic)this.ic=new He(this.sa.ab());e=this.ic.Q;e.top=this.sa.top;e.right=this.sa.right;e.bottom=this.sa.bottom;e.left=this.sa.left;for(b=0;d=this.vb[b];b++){d=d.Q;f=-1;if(a>=d.right)f=d.right>
e.left?d.right:e.left;else if(a<d.left)f=d.left<e.right?d.left:e.right;var h=-1;if(c>=d.bottom)h=d.bottom>e.top?d.bottom:e.top;else if(c<d.top)h=d.top<e.bottom?d.top:e.bottom;if(f>=0&&h>=0)if(Math.abs(f-a)>Math.abs(h-c))h=-1;else f=-1;if(f>=0)if(f<=a)e.left=f;else e.right=f;else if(h>=0)if(h<=c)e.top=h;else e.bottom=h}this.Pa=(e.right-e.left)*(e.bottom-e.top)>=10?this.ic:j}}};q.Td=p(l);
q.Zc=function(a){for(var b=0,c;c=this.Rb[b];b++)if(a.target==c.a){var d=c.Ld-c.a.scrollTop,e=c.Kd-c.a.scrollLeft;c.Ld=c.a.scrollTop;c.Kd=c.a.scrollLeft;for(var f=0,h;h=c.dc[f];f++){h.Q.top+=d;h.Q.left+=e;h.Q.bottom+=d;h.Q.right+=e}}};function Ie(a,b,c,d){return b>=d.left&&b<d.right&&c>=d.top&&c<d.bottom}q.f=function(){Ce.c.f.call(this);for(var a,b=0;a=this.ya[b];b++)Fe(this,a);this.ya.length=0};
function Ge(a,b,c,d,e,f,h,k,m,o,w){C.call(this,a);this.ne=b;this.Cb=c;this.oe=d;this.hc=e;this.pe=f;this.clientX=h;this.clientY=k;this.Ff=m;this.Gf=o;this.kf=w}v(Ge,C);Ge.prototype.f=function(){Ge.c.f.call(this);delete this.ne;delete this.Cb;delete this.oe;delete this.hc;delete this.pe};function Je(a,b){this.element=P(a);this.data=b;this.l=j;if(!this.element)g(Error("Invalid argument"))}v(Je,I);q=Je.prototype;q.Qa=j;
q.xd=function(a){var b=a.target;if(b){F(b,"mousemove",this.Ya,l,this);F(b,"mouseout",this.Ya,l,this);F(b,"mouseup",this.Cc,l,this);this.Qa=b;this.Pc=new Bc(a.clientX,a.clientY);a.preventDefault()}};q.rb=ba("l");q.Ya=function(a){if(Math.abs(a.clientX-this.Pc.x)+Math.abs(a.clientY-this.Pc.y)>5){var b=this.Qa;G(b,"mousemove",this.Ya,l,this);G(b,"mouseout",this.Ya,l,this);G(b,"mouseup",this.Cc,l,this);this.l.tb(a,this)}};
q.Cc=function(){var a=this.Qa;G(a,"mousemove",this.Ya,l,this);G(a,"mouseout",this.Ya,l,this);G(a,"mouseup",this.Cc,l,this);delete this.Pc;this.Qa=j};function He(a,b,c,d){this.Q=a;this.h=b;this.ra=c;this.a=d}He.prototype.Jc=j;function Ke(a,b){Ce.call(this);var c=new Je(a,b);c.rb(this);this.ya.push(c)}v(Ke,Ce);function X(a){this.q=a||N();this.mb=Le}v(X,I);X.prototype.Je=rd.ka();var Le=j;function Me(a,b){switch(a){case 1:return b?"disable":"enable";case 2:return b?"highlight":"unhighlight";case 4:return b?"activate":"deactivate";case 8:return b?"select":"unselect";case 16:return b?"check":"uncheck";case 32:return b?"focus":"blur";case 64:return b?"open":"close"}g(Error("Invalid component state"))}q=X.prototype;q.Va=j;q.n=l;q.a=j;q.mb=j;q.Qe=j;q.l=j;q.G=j;q.Z=j;q.$d=l;
function Ne(a){return a.Va||(a.Va=sd(a.Je))}function Oe(a,b){if(a.l&&a.l.Z){ib(a.l.Z,a.Va);jb(a.l.Z,b,a)}a.Va=b}q.b=ca("a");q.ca=function(){return this.Ua||(this.Ua=new Md(this))};q.rb=function(a){if(this==a)g(Error("Unable to set parent component"));if(a&&this.l&&this.Va&&Pe(this.l,this.Va)&&this.l!=a)g(Error("Unable to set parent component"));this.l=a;X.c.Lc.call(this,a)};q.Lc=function(a){if(this.l&&this.l!=a)g(Error("Method not supported"));X.c.Lc.call(this,a)};q.m=ca("q");
q.e=function(){this.a=this.q.createElement("div")};q.ma=function(a){Qe(this,a)};function Qe(a,b,c){if(a.n)g(Error("Component already rendered"));a.a||a.e();b?b.insertBefore(a.a,c||j):a.q.u.body.appendChild(a.a);if(!a.l||a.l.n)a.N()}q.$=function(a){if(this.n)g(Error("Component already rendered"));else if(a&&this.oa(a)){this.$d=i;if(!this.q||this.q.u!=O(a))this.q=N(a);this.cb(a);this.N()}else g(Error("Invalid element to decorate"))};q.oa=p(i);q.cb=ba("a");
q.N=function(){this.n=i;Re(this,function(a){!a.n&&a.b()&&a.N()})};q.qa=function(){Re(this,function(a){a.n&&a.qa()});this.Ua&&this.Ua.removeAll();this.n=l};q.f=function(){X.c.f.call(this);this.n&&this.qa();if(this.Ua){this.Ua.i();delete this.Ua}Re(this,function(a){a.i()});!this.$d&&this.a&&Tc(this.a);this.l=this.Qe=this.a=this.Z=this.G=j};q.Yb=function(a,b){this.Zb(a,Se(this),b)};
q.Zb=function(a,b,c){if(a.n&&(c||!this.n))g(Error("Component already rendered"));if(b<0||b>Se(this))g(Error("Child component index out of bounds"));if(!this.Z||!this.G){this.Z={};this.G=[]}if(a.l==this){this.Z[Ne(a)]=a;xb(this.G,a)}else jb(this.Z,Ne(a),a);a.rb(this);Ab(this.G,b,0,a);if(a.n&&this.n&&a.l==this){c=this.S();c.insertBefore(a.b(),c.childNodes[b]||j)}else if(c){this.a||this.e();b=Y(this,b+1);Qe(a,this.S(),b?b.a:j)}else this.n&&!a.n&&a.a&&a.N()};q.S=ca("a");
function Te(a){if(a.mb==j)a.mb="rtl"==ed(a.n?a.a:a.q.u.body,"direction");return a.mb}q.sb=function(a){if(this.n)g(Error("Component already rendered"));this.mb=a};function Se(a){return a.G?a.G.length:0}function Pe(a,b){var c;if(a.Z&&b){c=a.Z;c=b in c?c[b]:void 0;c=c||j}else c=j;return c}function Y(a,b){return a.G?a.G[b]||j:j}function Re(a,b,c){a.G&&sb(a.G,b,c)}function Ue(a,b){return a.G&&b?rb(a.G,b):-1}
q.removeChild=function(a,b){if(a){var c=t(a)?a:Ne(a);a=Pe(this,c);if(c&&a){ib(this.Z,c);xb(this.G,a);if(b){a.qa();a.a&&Tc(a.a)}a.rb(j)}}if(!a)g(Error("Child is not in parent component"));return a};q.Jd=function(a){for(;this.G&&this.G.length!=0;)this.removeChild(Y(this,0),a)};function Ve(a){this.a=a;a=x?"focusout":"blur";this.Me=F(this.a,x?"focusin":"focus",this,!x);this.Ne=F(this.a,a,this,!x)}v(Ve,I);Ve.prototype.handleEvent=function(a){var b=new Ib(a.ja);b.type=a.type=="focusin"||a.type=="focus"?"focusin":"focusout";try{this.dispatchEvent(b)}finally{b.i()}};Ve.prototype.f=function(){Ve.c.f.call(this);H(this.Me);H(this.Ne);delete this.a};function We(a,b,c){X.call(this,c);this.t=a||"modal-dialog";this.Sc=!!b;this.F=Xe()}v(We,X);q=We.prototype;q.Db=j;q.qe=i;q.qc=i;q.Sc=l;q.Nb=i;q.cd=i;q.ge=0.5;q.Vb="";q.R="";q.F=j;q.J=j;q.g=l;q.ke=l;q.s=j;q.r=j;q.Y=j;q.na=j;q.Rc=j;q.ta=j;q.U=j;q.D=j;q.setTitle=function(a){this.Vb=a;this.na&&Wc(this.na,a)};q.pb=function(a){this.R=a;if(this.U)this.U.innerHTML=a};q.S=function(){this.b()||this.ma();return this.U};
q.e=function(){Ye(this);var a=this.m();this.a=a.e("div",{className:this.t,tabIndex:0},this.Y=a.e("div",{className:this.t+"-title",id:Ne(this)},this.na=a.e("span",this.t+"-title-text",this.Vb),this.ta=a.e("span",this.t+"-title-close")),this.U=a.e("div",this.t+"-content"),this.D=a.e("div",this.t+"-buttons"),this.Ud=a.e("span",{tabIndex:0}));this.Rc=this.Y.id;yd(this.b(),"dialog");zd(this.b(),"labelledby",this.Rc||"");if(this.R)this.U.innerHTML=this.R;Q(this.ta,this.qc);Q(this.b(),l);if(this.F){a=this.F;
a.a=this.D;a.ma()}};function Ye(a){if(a.Sc&&a.Nb&&!a.r){var b;b=a.m().e("iframe",{frameborder:0,style:"border:0;vertical-align:bottom;",src:'javascript:""'});a.r=b;a.r.className=a.t+"-bg";Q(a.r,l);md(a.r,0)}else if((!a.Sc||!a.Nb)&&a.r){Tc(a.r);a.r=j}if(a.Nb&&!a.s){a.s=a.m().e("div",a.t+"-bg");md(a.s,a.ge);Q(a.s,l)}else if(!a.Nb&&a.s){Tc(a.s);a.s=j}}q.ma=function(a){if(this.n)g(Error("Component already rendered"));this.b()||this.e();a=a||bd(this.m()).body;Ze(this,a);We.c.ma.call(this,a)};
function Ze(a,b){a.r&&b.appendChild(a.r);a.s&&b.appendChild(a.s)}q.oa=function(a){return a&&a.tagName&&a.tagName=="DIV"&&We.c.oa.call(this,a)};
q.cb=function(a){We.c.cb.call(this,a);M(this.b(),this.t);a=this.t+"-content";if(this.U=Jc(document,j,a,this.b())[0])this.R=this.U.innerHTML;else{this.U=this.m().e("div",a);if(this.R)this.U.innerHTML=this.R;this.b().appendChild(this.U)}a=this.t+"-title";var b=this.t+"-title-text",c=this.t+"-title-close";if(this.Y=Jc(document,j,a,this.b())[0]){this.na=Jc(document,j,b,this.Y)[0];this.ta=Jc(document,j,c,this.Y)[0]}else{this.Y=this.m().e("div",a);this.b().insertBefore(this.Y,this.U)}if(this.na)this.Vb=
$c(this.na);else{this.na=this.m().e("span",b,this.Vb);this.Y.appendChild(this.na)}zd(this.b(),"labelledby",this.Rc||"");if(!this.ta){this.ta=this.m().e("span",c);this.Y.appendChild(this.ta)}Q(this.ta,this.qc);a=this.t+"-buttons";if(this.D=Jc(document,j,a,this.b())[0]){this.F=new $e(this.m());this.F.$(this.D)}else{this.D=this.m().e("div",a);this.b().appendChild(this.D);if(this.F){a=this.F;a.a=this.D;a.ma()}}Ye(this);Ze(this,O(this.b()).body);Q(this.b(),l)};
q.N=function(){We.c.N.call(this);this.Db=new Ve(bd(this.m()));if(this.cd&&!this.J){var a=new ue(this.b(),this.Y);M(this.Y,this.t+"-title-draggable");this.J=a}R(R(this.ca(),this.ta,"click",this.We),this.Db,"focusin",this.Te);yd(this.b(),"dialog");this.na.id!==""&&zd(this.b(),"labelledby",this.na.id)};q.qa=function(){this.g&&this.P(l);this.Db.i();this.Db=j;if(this.J){this.J.i();this.J=j}We.c.qa.call(this)};
q.P=function(a){if(a!=this.g){var b=bd(this.m()),c=(b?b.parentWindow||b.defaultView:window)||window;this.n||this.ma(b.body);if(a){af(this);this.Gc();R(R(R(this.ca(),this.b(),"keydown",this.Na),this.b(),"keypress",this.Na),c,"resize",this.Fd)}else S(S(S(this.ca(),this.b(),"keydown",this.Na),this.b(),"keypress",this.Na),c,"resize",this.Fd);this.r&&Q(this.r,a);this.s&&Q(this.s,a);Q(this.b(),a);a&&this.focus();if(this.g=a)R(this.ca(),this.D,"click",this.Ad);else{S(this.ca(),this.D,"click",this.Ad);this.dispatchEvent(bf);
this.ke&&this.i()}}};q.focus=function(){try{this.b().focus()}catch(a){}if(this.F){var b=this.F.db;if(b)for(var c=bd(this.m()),d=this.D.getElementsByTagName("button"),e=0,f;f=d[e];e++)if(f.name==b){try{if(z||Ta){var h=c.createElement("input");h.style.cssText="position:fixed;width:0;height:0;left:0;top:0;";this.b().appendChild(h);h.focus();this.b().removeChild(h)}f.focus()}catch(k){}break}}};
function af(a){a.r&&Q(a.r,l);a.s&&Q(a.s,l);var b=bd(a.m()),c=Nc((b?b.parentWindow||b.defaultView:window)||window||window),d=Math.max(b.body.scrollWidth,c.width);b=Math.max(b.body.scrollHeight,c.height);if(a.r){Q(a.r,i);kd(a.r,d,b)}if(a.s){Q(a.s,i);kd(a.s,d,b)}if(a.cd){c=ld(a.b());a.J.Bc=new Cc(0,0,d-c.width,b-c.height)}}
q.Gc=function(){var a=bd(this.m()),b=(a?a.parentWindow||a.defaultView:window)||window;if(ed(this.b(),"position")=="fixed")var c=a=0;else{c=cd(this.m());a=c.x;c=c.y}var d=ld(this.b());b=Nc(b||window);fd(this.b(),Math.max(a+b.width/2-d.width/2,0),Math.max(c+b.height/2-d.height/2,0))};q.We=function(){if(this.qc){var a=this.F,b=a&&a.cc;if(b){a=a.get(b);this.dispatchEvent(new cf(b,a))&&this.P(l)}else this.P(l)}};
q.f=function(){We.c.f.call(this);if(this.s){Tc(this.s);this.s=j}if(this.r){Tc(this.r);this.r=j}this.Ud=this.D=this.ta=j};q.Ad=function(a){a:{for(a=a.target;a!=j&&a!=this.D;){if(a.tagName=="BUTTON"){a=a;break a}a=a.parentNode}a=j}if(a&&!a.disabled){a=a.name;var b=this.F.get(a);this.dispatchEvent(new cf(a,b))&&this.P(l)}};
q.Na=function(a){var b=l,c=l,d=this.F,e=a.target;if(a.type=="keydown")if(this.qe&&a.keyCode==27){var f=d&&d.cc;e=e.tagName=="SELECT"&&!e.disabled;if(f&&!e){c=i;b=d.get(f);b=this.dispatchEvent(new cf(f,b))}else e||(b=i)}else{if(a.keyCode==9&&a.shiftKey&&e==this.b())c=i}else if(a.keyCode==13){if(e.tagName=="BUTTON")f=e.name;else if(d){var h=d.db,k;if(k=h)a:{k=d.a.getElementsByTagName("BUTTON");for(var m=0,o;o=k[m];m++)if(o.name==h||o.id==h){k=o;break a}k=j}k=k;e=(e.tagName=="TEXTAREA"||e.tagName=="SELECT")&&
!e.disabled;if(k&&!k.disabled&&!e)f=h}if(f){c=i;b=this.dispatchEvent(new cf(f,String(d.get(f))))}}if(b||c){a.stopPropagation();a.preventDefault()}b&&this.P(l)};q.Fd=function(){af(this)};q.Te=function(a){this.Ud==a.target&&Ld(this.se,0,this)};q.se=function(){x&&bd(this.m()).body.focus();this.b().focus()};function cf(a,b){this.type=df;this.key=a;this.caption=b}v(cf,C);var df="dialogselect",bf="afterhide";function $e(a){this.q=a||N();ge.call(this)}v($e,ge);q=$e.prototype;q.t="goog-buttonset";q.db=j;
q.a=j;q.cc=j;q.set=function(a,b,c,d){ge.prototype.set.call(this,a,b);if(c)this.db=a;if(d)this.cc=a;return this};function ef(a,b,c,d){return a.set(b.key,b.caption,c,d)}q.ma=function(){if(this.a){this.a.innerHTML="";var a=N(this.a);fe(this,function(b,c){var d=a.e("button",{name:c},b);if(c==this.db)d.className=this.t+"-default";this.a.appendChild(d)},this)}};
q.$=function(a){if(!(!a||a.nodeType!=1)){this.a=a;a=this.a.getElementsByTagName("button");for(var b=0,c,d,e;c=a[b];b++){d=c.name||c.id;e=$c(c)||c.value;if(d){var f=b==0;this.set(d,e,f,c.name==ff);f&&M(c,this.t+"-default")}}}};var ff="cancel",gf=sa("OK"),hf=sa("Cancel"),jf=sa("Yes"),kf=sa("No"),lf=sa("Save"),mf=sa("Continue"),nf={key:"ok",caption:gf},of={key:ff,caption:hf},pf={key:"yes",caption:jf},qf={key:"no",caption:kf},rf={key:"save",caption:lf},sf={key:"continue",caption:mf};
function Xe(){return ef(ef(new $e,nf,i),of,l,i)}ef(new $e,nf,i,i);Xe();ef(ef(new $e,pf,i),qf,l,i);ef(ef(ef(new $e,pf),qf,i),of,l,i);ef(ef(ef(new $e,sf),rf),of,i,i);function tf(a,b,c,d,e,f,h){We.call(this,e,f,h);this.setTitle(a);this.pb(b+"<br><br>");this.bc=c;this.ec=d!==undefined?d:"";F(this,df,this.Ed);a=sa("OK");b=sa("Cancel");h=new $e(h);h.set("ok",a,i);h.set(ff,b,l,i);this.F=h;if(this.D)if(this.F){h=this.F;h.a=this.D;h.ma()}else this.D.innerHTML=""}v(tf,We);q=tf.prototype;q.bc=ea;q.ec="";q.T=j;q.uc=l;q.o=1;q.Bb=0;
q.e=function(){tf.c.e.call(this);var a={className:this.t+"-userInput",value:this.ec};if(this.o==1){this.T=this.m().e("input",a);this.T.type="text";if(this.Bb)this.T.size=this.Bb}else{this.T=this.m().e("textarea",a);this.T.rows=this.o;if(this.Bb)this.T.cols=this.Bb}this.S().appendChild(this.m().e("div",{style:"overflow: auto"},this.T));if(this.o>1)this.F.db=j};q.P=function(a){We.prototype.P.call(this,a);if(a){this.uc=l;this.T.value=this.ec;this.focus()}};q.focus=function(){Ta&&this.T.focus();this.T.select()};
q.Ed=function(a){if(!this.uc){this.uc=i;a.key=="ok"?Ld(pa(this.bc,this,this.T.value),1):Ld(pa(this.bc,this,j),1)}};q.f=function(){Tc(this.T);G(this,df,this.Ed,i,this);tf.c.f.call(this);this.T=this.yf=j};function uf(){Ce.call(this)}v(uf,Ce);uf.prototype.Wc=function(a,b){var c=new Je(a,b);c.rb(this);this.ya.push(c);this.tc&&Ee(this,c)};uf.prototype.removeItem=function(a){a=P(a);for(var b,c=0;b=this.ya[c];c++)if(b.element==a){this.ya.splice(c,1);Fe(this,b);break}};function vf(){}var wf;fa(vf);q=vf.prototype;q.Ta=aa();q.e=function(a){return a.m().e("div",this.hb(a).join(" "),a.R)};q.S=function(a){return a};q.gb=function(a,b,c){if(a=a.b?a.b():a)if(x&&!A("7")){var d=xf(this,Ec(a),b);d.push(b);qa(c?M:Fc,a).apply(j,d)}else c?M(a,b):Fc(a,b)};q.oa=p(i);
q.$=function(a,b){b.id&&Oe(a,b.id);var c=this.S(b);if(c&&c.firstChild)yf(a,c.firstChild.nextSibling?zb(c.childNodes):c.firstChild);else a.R=j;var d=0,e=this.L(),f=this.L(),h=l,k=l;c=l;var m=Ec(b);sb(m,function(n){if(!h&&n==e){h=i;if(f==e)k=i}else if(!k&&n==f)k=i;else{var u=d;if(!this.Rd){this.Ab||zf(this);this.Rd=kb(this.Ab)}n=parseInt(this.Rd[n],10);d=u|(isNaN(n)?0:n)}},this);a.B=d;if(!h){m.push(e);if(f==e)k=i}k||m.push(f);var o=a.ba;o&&m.push.apply(m,o);if(x&&!A("7")){var w=xf(this,m);if(w.length>
0){m.push.apply(m,w);c=i}}if(!h||!k||o||c)b.className=m.join(" ");return b};q.sc=function(a){Te(a)&&this.sb(a.b(),i);a.w()&&this.qb(a,a.g)};q.Tb=function(a,b){od(a,!b,!x&&!Ta)};q.sb=function(a,b){this.gb(a,this.L()+"-rtl",b)};q.Ka=function(a){var b;if(a.X&32&&(b=a.H()))return Zc(b);return l};q.qb=function(a,b){var c;if(a.X&32&&(c=a.H())){if(!b&&a.B&32){try{c.blur()}catch(d){}a.B&32&&a.Ja(j)}if(Zc(c)!=b){c=c;if(b)c.tabIndex=0;else c.removeAttribute("tabIndex")}}};q.P=function(a,b){Q(a,b)};
q.W=function(a,b,c){var d=a.b();if(d){var e=Af(this,b);e&&this.gb(a,e,c);if(y){wf||(wf=nb(1,"disabled",4,"pressed",8,"selected",16,"checked",64,"expanded"));(a=wf[b])&&zd(d,a,c)}}};q.pb=function(a,b){var c=this.S(a);if(c){Sc(c);if(b)if(t(b))Wc(c,b);else{var d=function(e){if(e){var f=O(c);c.appendChild(t(e)?f.createTextNode(e):e)}};if(s(b))sb(b,d);else ha(b)&&!("nodeType"in b)?sb(zb(b),d):d(b)}}};q.H=function(a){return a.b()};q.L=p("goog-control");
q.hb=function(a){var b=this.L(),c=[b],d=this.L();d!=b&&c.push(d);b=a.B;for(d=[];b;){var e=b&-b;d.push(Af(this,e));b&=~e}c.push.apply(c,d);(a=a.ba)&&c.push.apply(c,a);x&&!A("7")&&c.push.apply(c,xf(this,c));return c};function xf(a,b,c){var d=[];if(c)b=b.concat([c]);sb([],function(e){if(vb(e,qa(wb,b))&&(!c||wb(e,c)))d.push(e.join("_"))});return d}function Af(a,b){a.Ab||zf(a);return a.Ab[b]}
function zf(a){var b=a.L();a.Ab=nb(1,b+"-disabled",2,b+"-hover",4,b+"-active",8,b+"-selected",16,b+"-checked",32,b+"-focused",64,b+"-open")};function Bf(a,b){if(!a)g(Error("Invalid class name "+a));if(!ia(b))g(Error("Invalid decorator function "+b));Cf[a]=b}var Df={},Cf={};function Z(a,b,c){X.call(this,c);if(!(b=b)){b=this.constructor;for(var d;b;){d=ka(b);if(d=Df[d])break;b=b.c?b.c.constructor:j}b=d?ia(d.ka)?d.ka():new d:j}this.d=b;this.R=a}v(Z,X);q=Z.prototype;q.R=j;q.B=0;q.X=39;q.fe=255;q.Ub=0;q.g=i;q.ba=j;q.jb=i;q.yb=l;q.H=function(){return this.d.H(this)};q.Eb=function(){return this.A||(this.A=new Qd)};
q.gb=function(a,b){if(b){if(a){if(this.ba)wb(this.ba,a)||this.ba.push(a);else this.ba=[a];this.d.gb(this,a,i)}}else if(a&&this.ba){xb(this.ba,a);if(this.ba.length==0)this.ba=j;this.d.gb(this,a,l)}};q.e=function(){var a=this.d.e(this);this.a=a;var b=this.d.Ta();b&&yd(a,b);this.yb||this.d.Tb(a,l);this.g||this.d.P(a,l)};q.S=function(){return this.d.S(this.b())};q.oa=function(a){return this.d.oa(a)};
q.cb=function(a){this.a=a=this.d.$(this,a);var b=this.d.Ta();b&&yd(a,b);this.yb||this.d.Tb(a,l);this.g=a.style.display!="none"};q.N=function(){Z.c.N.call(this);this.d.sc(this);if(this.X&-2){this.jb&&Ef(this,i);if(this.X&32){var a=this.H();if(a){var b=this.Eb();Rd(b,a);R(R(R(this.ca(),b,"key",this.la),a,"focus",this.wa),a,"blur",this.Ja)}}}};
function Ef(a,b){var c=a.ca(),d=a.b();if(b){R(R(R(R(c,d,"mouseover",a.oc),d,"mousedown",a.ib),d,"mouseup",a.pc),d,"mouseout",a.nc);x&&R(c,d,"dblclick",a.gd)}else{S(S(S(S(c,d,"mouseover",a.oc),d,"mousedown",a.ib),d,"mouseup",a.pc),d,"mouseout",a.nc);x&&S(c,d,"dblclick",a.gd)}}q.qa=function(){Z.c.qa.call(this);this.A&&this.A.detach();this.g&&this.w()&&this.d.qb(this,l)};q.f=function(){Z.c.f.call(this);if(this.A){this.A.i();delete this.A}delete this.d;this.ba=this.R=j};
q.pb=function(a){this.d.pb(this.b(),a);this.R=a};function yf(a,b){a.R=b}q.sb=function(a){Z.c.sb.call(this,a);var b=this.b();b&&this.d.sb(b,a)};q.Tb=function(a){this.yb=a;var b=this.b();b&&this.d.Tb(b,a)};q.P=function(a,b){if(b||this.g!=a&&this.dispatchEvent(a?"show":"hide")){var c=this.b();c&&this.d.P(c,a);this.w()&&this.d.qb(this,a);this.g=a;return i}return l};q.w=function(){return!(this.B&1)};
q.setEnabled=function(a){var b=this.l;if(!(b&&typeof b.w=="function"&&!b.w())&&Ff(this,1,!a)){if(!a){this.setActive(l);this.ga(l)}this.g&&this.d.qb(this,a);this.W(1,!a)}};q.ga=function(a){Ff(this,2,a)&&this.W(2,a)};q.setActive=function(a){Ff(this,4,a)&&this.W(4,a)};function Gf(a,b){Ff(a,8,b)&&a.W(8,b)}q.La=function(){return!!(this.B&64)};function Hf(a,b){Ff(a,64,b)&&a.W(64,b)}q.W=function(a,b){if(this.X&a&&b!=!!(this.B&a)){this.d.W(this,a,b);this.B=b?this.B|a:this.B&~a}};
function If(a,b,c){if(a.n&&a.B&b&&!c)g(Error("Component already rendered"));!c&&a.B&b&&a.W(b,l);a.X=c?a.X|b:a.X&~b}function $(a,b){return!!(a.fe&b)&&!!(a.X&b)}function Ff(a,b,c){return!!(a.X&b)&&!!(a.B&b)!=c&&(!(a.Ub&b)||a.dispatchEvent(Me(b,c)))&&!a.gc}q.oc=function(a){!(a.relatedTarget&&Vc(this.b(),a.relatedTarget))&&this.dispatchEvent("enter")&&this.w()&&$(this,2)&&this.ga(i)};
q.nc=function(a){if(!(a.relatedTarget&&Vc(this.b(),a.relatedTarget))&&this.dispatchEvent("leave")){$(this,4)&&this.setActive(l);$(this,2)&&this.ga(l)}};q.ib=function(a){if(this.w()){$(this,2)&&this.ga(i);if(Kb(a,0)){$(this,4)&&this.setActive(i);this.d.Ka(this)&&this.H().focus()}}!this.yb&&Kb(a,0)&&a.preventDefault()};q.pc=function(a){if(this.w()){$(this,2)&&this.ga(i);this.B&4&&Jf(this,a)&&$(this,4)&&this.setActive(l)}};q.gd=function(a){this.w()&&Jf(this,a)};
function Jf(a,b){if($(a,16)){var c=!(a.B&16);Ff(a,16,c)&&a.W(16,c)}$(a,8)&&Gf(a,i);$(a,64)&&Hf(a,!a.La());c=new C("action",a);if(b)for(var d=["altKey","ctrlKey","metaKey","shiftKey","platformModifierKey"],e,f=0;e=d[f];f++)c[e]=b[e];return a.dispatchEvent(c)}q.wa=function(){$(this,32)&&Ff(this,32,i)&&this.W(32,i)};q.Ja=function(){$(this,4)&&this.setActive(l);$(this,32)&&Ff(this,32,l)&&this.W(32,l)};q.la=function(a){if(this.g&&this.w()&&this.mc(a)){a.preventDefault();a.stopPropagation();return i}return l};
q.mc=function(a){return a.keyCode==13&&Jf(this,a)};if(!ia(Z))g(Error("Invalid component class "+Z));if(!ia(vf))g(Error("Invalid renderer class "+vf));var Kf=ka(Z);Df[Kf]=vf;Bf("goog-control",function(){return new Z(j)});function Lf(){}v(Lf,vf);fa(Lf);q=Lf.prototype;q.L=p("goog-tab");q.Ta=p("tab");q.e=function(a){var b=Lf.c.e.call(this,a);(a=a.lc())&&this.Nc(b,a);return b};q.$=function(a,b){b=Lf.c.$.call(this,a,b);var c=this.lc(b);if(c)a.Wd=c;if(a.B&8)if((c=a.l)&&ia(c.Da)){a.W(8,l);c.Da(a)}return b};q.lc=function(a){return a.title||""};q.Nc=function(a,b){if(a)a.title=b||""};function Mf(a,b,c){Z.call(this,a,b||Lf.ka(),c);If(this,8,i);this.Ub|=9}v(Mf,Z);Mf.prototype.lc=ca("Wd");Mf.prototype.Nc=function(a){this.d.Nc(this.b(),a);this.Wd=a};Bf("goog-tab",function(){return new Mf(j)});function Nf(){}v(Nf,vf);fa(Nf);Nf.prototype.e=function(a){return a.m().e("div",this.L())};Nf.prototype.$=function(a,b){if(b.tagName=="HR"){var c=b;b=this.e(a);c.parentNode&&c.parentNode.insertBefore(b,c);Tc(c)}else M(b,this.L());return b};Nf.prototype.pb=aa();Nf.prototype.L=p("goog-menuseparator");function Of(a,b){Z.call(this,j,a||Nf.ka(),b);If(this,1,l);If(this,2,l);If(this,4,l);If(this,32,l);this.B=1}v(Of,Z);Of.prototype.N=function(){Of.c.N.call(this);yd(this.b(),"separator")};Bf("goog-menuseparator",function(){return new Of});function Pf(){}fa(Pf);q=Pf.prototype;q.Ta=aa();function Qf(a,b,c){if(b)b.tabIndex=c?0:-1}q.e=function(a){return a.m().e("div",this.hb(a).join(" "))};q.S=function(a){return a};q.oa=function(a){return a.tagName=="DIV"};q.$=function(a,b){b.id&&Oe(a,b.id);var c=this.L(),d=l,e=Ec(b);e&&sb(e,function(f){if(f==c)d=i;else f&&this.Mc(a,f,c)},this);d||M(b,c);Rf(this,a,this.S(b));return b};
q.Mc=function(a,b,c){if(b==c+"-disabled")a.setEnabled(l);else if(b==c+"-horizontal")Sf(a,Tf);else b==c+"-vertical"&&Sf(a,Uf)};function Rf(a,b,c,d){if(c)for(a=d||c.firstChild;a&&a.parentNode==c;){d=a.nextSibling;if(a.nodeType==1){var e;a:{e=void 0;for(var f=Ec(a),h=0,k=f.length;h<k;h++)if(e=f[h]in Cf?Cf[f[h]]():j){e=e;break a}e=j}if(e){e.a=a;b.w()||e.setEnabled(l);b.Yb(e);e.$(a)}}else if(!a.nodeValue||za(a.nodeValue)=="")c.removeChild(a);a=d}}
q.sc=function(a){a=a.b();od(a,i,y);if(x)a.hideFocus=i;var b=this.Ta();b&&yd(a,b)};q.H=function(a){return a.b()};q.L=p("goog-container");q.hb=function(a){var b=this.L(),c=[b,a.Ca==Tf?b+"-horizontal":b+"-vertical"];a.w()||c.push(b+"-disabled");return c};function Vf(){}v(Vf,Pf);fa(Vf);Vf.prototype.L=p("goog-tab-bar");Vf.prototype.Ta=p("tablist");Vf.prototype.Mc=function(a,b,c){if(!this.td){this.zb||Wf(this);this.td=kb(this.zb)}var d=this.td[b];if(d){Sf(a,d==Xf||d==Yf?Uf:Tf);a.ud=d}else Vf.c.Mc.call(this,a,b,c)};Vf.prototype.hb=function(a){var b=Vf.c.hb.call(this,a);this.zb||Wf(this);b.push(this.zb[a.ud]);return b};function Wf(a){var b=a.L();a.zb=nb(Zf,b+"-top",$f,b+"-bottom",Xf,b+"-start",Yf,b+"-end")};function ag(a,b,c){X.call(this,c);this.d=b||Pf.ka();this.Ca=a||Uf}v(ag,X);var Tf="horizontal",Uf="vertical";q=ag.prototype;q.pd=j;q.A=j;q.d=j;q.Ca=j;q.g=i;q.aa=i;q.kc=i;q.z=-1;q.v=j;q.Xa=l;q.ce=l;q.Xe=i;q.ua=j;q.H=function(){return this.pd||this.d.H(this)};q.Eb=function(){return this.A||(this.A=new Qd(this.H()))};q.e=function(){this.a=this.d.e(this)};q.S=function(){return this.d.S(this.b())};q.oa=function(a){return this.d.oa(a)};
q.cb=function(a){this.a=this.d.$(this,a);if(a.style.display=="none")this.g=l};q.N=function(){ag.c.N.call(this);Re(this,function(b){b.n&&bg(this,b)},this);var a=this.b();this.d.sc(this);this.P(this.g,i);R(R(R(R(R(R(R(R(this.ca(),this,"enter",this.xe),this,"highlight",this.ye),this,"unhighlight",this.He),this,"open",this.Ce),this,"close",this.ve),a,"mousedown",this.ib),O(a),"mouseup",this.we),a,["mousedown","mouseup","mouseover","mouseout"],this.ue);this.Ka()&&cg(this,i)};
function cg(a,b){var c=a.ca(),d=a.H();b?R(R(R(c,d,"focus",a.wa),d,"blur",a.Ja),a.Eb(),"key",a.la):S(S(S(c,d,"focus",a.wa),d,"blur",a.Ja),a.Eb(),"key",a.la)}q.qa=function(){dg(this,-1);this.v&&Hf(this.v,l);this.Xa=l;ag.c.qa.call(this)};q.f=function(){ag.c.f.call(this);if(this.A){this.A.i();this.A=j}this.d=this.v=this.ua=j};q.xe=p(i);
q.ye=function(a){var b=Ue(this,a.target);if(b>-1&&b!=this.z){var c=Y(this,this.z);c&&c.ga(l);this.z=b;c=Y(this,this.z);this.Xa&&c.setActive(i);if(this.Xe&&this.v&&c!=this.v)c.X&64?Hf(c,i):Hf(this.v,l)}zd(this.b(),"activedescendant",a.target.b().id)};q.He=function(a){if(a.target==Y(this,this.z))this.z=-1;zd(this.b(),"activedescendant","")};q.Ce=function(a){if((a=a.target)&&a!=this.v&&a.l==this){this.v&&Hf(this.v,l);this.v=a}};q.ve=function(a){if(a.target==this.v)this.v=j};
q.ib=function(a){if(this.aa)this.Xa=i;var b=this.H();b&&Zc(b)?b.focus():a.preventDefault()};q.we=function(){this.Xa=l};q.ue=function(a){var b;a:{b=a.target;if(this.ua)for(var c=this.b();b&&b!==c;){var d=b.id;if(d in this.ua){b=this.ua[d];break a}b=b.parentNode}b=j}if(b)switch(a.type){case "mousedown":b.ib(a);break;case "mouseup":b.pc(a);break;case "mouseover":b.oc(a);break;case "mouseout":b.nc(a)}};q.wa=aa();q.Ja=function(){dg(this,-1);this.Xa=l;this.v&&Hf(this.v,l)};
q.la=function(a){if(this.w()&&this.g&&(Se(this)!=0||this.pd)&&this.mc(a)){a.preventDefault();a.stopPropagation();return i}return l};
q.mc=function(a){var b=Y(this,this.z);if(b&&typeof b.la=="function"&&b.la(a))return i;if(this.v&&this.v!=b&&typeof this.v.la=="function"&&this.v.la(a))return i;if(a.shiftKey||a.ctrlKey||a.metaKey||a.altKey)return l;switch(a.keyCode){case 27:if(this.Ka())this.H().blur();else return l;break;case 36:eg(this);break;case 35:fg(this);break;case 38:if(this.Ca==Uf)gg(this);else return l;break;case 37:if(this.Ca==Tf)Te(this)?hg(this):gg(this);else return l;break;case 40:if(this.Ca==Uf)hg(this);else return l;
break;case 39:if(this.Ca==Tf)Te(this)?gg(this):hg(this);else return l;break;default:return l}return i};function bg(a,b){var c=b.b();c=c.id||(c.id=Ne(b));if(!a.ua)a.ua={};a.ua[c]=b}q.Yb=function(a,b){ag.c.Yb.call(this,a,b)};q.Zb=function(a,b,c){a.Ub|=2;a.Ub|=64;if(this.Ka()||!this.ce)If(a,32,l);a.n&&l!=a.jb&&Ef(a,l);a.jb=l;ag.c.Zb.call(this,a,b,c);c&&this.n&&bg(this,a);b<=this.z&&this.z++};
q.removeChild=function(a,b){if(a=t(a)?Pe(this,a):a){var c=Ue(this,a);if(c!=-1)if(c==this.z)a.ga(l);else c<this.z&&this.z--;(c=a.b())&&c.id&&ib(this.ua,c.id)}c=a=ag.c.removeChild.call(this,a,b);c.n&&i!=c.jb&&Ef(c,i);c.jb=i;return a};function Sf(a,b){if(a.b())g(Error("Component already rendered"));a.Ca=b}
q.P=function(a,b){if(b||this.g!=a&&this.dispatchEvent(a?"show":"hide")){this.g=a;var c=this.b();if(c){Q(c,a);this.Ka()&&Qf(this.d,this.H(),this.aa&&this.g);b||this.dispatchEvent(this.g?"aftershow":"afterhide")}return i}return l};q.w=ca("aa");
q.setEnabled=function(a){if(this.aa!=a&&this.dispatchEvent(a?"enable":"disable")){if(a){this.aa=i;Re(this,function(b){if(b.ae)delete b.ae;else b.setEnabled(i)})}else{Re(this,function(b){if(b.w())b.setEnabled(l);else b.ae=i});this.Xa=this.aa=l}this.Ka()&&Qf(this.d,this.H(),a&&this.g)}};q.Ka=ca("kc");q.qb=function(a){a!=this.kc&&this.n&&cg(this,a);this.kc=a;this.aa&&this.g&&Qf(this.d,this.H(),a)};function dg(a,b){var c=Y(a,b);if(c)c.ga(i);else a.z>-1&&Y(a,a.z).ga(l)}
q.ga=function(a){dg(this,Ue(this,a))};function eg(a){ig(a,function(b,c){return(b+1)%c},Se(a)-1)}function fg(a){ig(a,function(b,c){b--;return b<0?c-1:b},0)}function hg(a){ig(a,function(b,c){return(b+1)%c},a.z)}function gg(a){ig(a,function(b,c){b--;return b<0?c-1:b},a.z)}function ig(a,b,c){c=c<0?Ue(a,a.v):c;var d=Se(a);c=b.call(a,c,d);for(var e=0;e<=d;){var f=Y(a,c);if(f&&f.g&&f.w()&&f.X&2){a.Kc(c);return i}e++;c=b.call(a,c,d)}return l}q.Kc=function(a){dg(this,a)};function jg(a,b,c){a=a||Zf;Sf(this,a==Xf||a==Yf?Uf:Tf);this.ud=a;ag.call(this,this.Ca,b||Vf.ka(),c);kg(this)}v(jg,ag);var Zf="top",$f="bottom",Xf="start",Yf="end";q=jg.prototype;q.ee=i;q.fa=j;q.N=function(){jg.c.N.call(this);kg(this)};q.f=function(){jg.c.f.call(this);this.fa=j};q.removeChild=function(a,b){lg(this,a);return jg.c.removeChild.call(this,a,b)};q.Kc=function(a){jg.c.Kc.call(this,a);this.ee&&this.Da(Y(this,a))};q.Da=function(a){if(a)Gf(a,i);else this.fa&&Gf(this.fa,l)};
function lg(a,b){if(b&&b==a.fa){for(var c=Ue(a,b),d=c-1;b=Y(a,d);d--)if(b.g&&b.w()){a.Da(b);return}for(c=c+1;b=Y(a,c);c++)if(b.g&&b.w()){a.Da(b);return}a.Da(j)}}q.Fe=function(a){this.fa&&this.fa!=a.target&&Gf(this.fa,l);this.fa=a.target};q.Ge=function(a){if(a.target==this.fa)this.fa=j};q.De=function(a){lg(this,a.target)};q.Ee=function(a){lg(this,a.target)};q.wa=function(){Y(this,this.z)||this.ga(this.fa||Y(this,0))};
function kg(a){R(R(R(R(a.ca(),a,"select",a.Fe),a,"unselect",a.Ge),a,"disable",a.De),a,"hide",a.Ee)}Bf("goog-tab-bar",function(){return new jg});da("oplop.options.onLoad",function(){mg=new jg;mg.$(P("tab_bar"));F(mg,"select",function(d){P(Ne(d.target)+"_content").style.display="block"});F(mg,"unselect",function(d){P(Ne(d.target)+"_content").style.display="none"});ng=new uf;og=new Ke("trashcan");var a=ua(),b;for(b in a)pg(b);De(ng,og);ng.xa();og.xa();var c=new tf("New Nickname","What nickname would you like to add?",qg);a=P("nicknamesSaveDrag");a.addEventListener("dragstart",rg,l);a.addEventListener("dragend",sg,l);F(P("newNicknamePrompt"),
"click",function(){c.P(i)});F(ng,"dragstart",function(d){md(d.Cb.element,0.5)});F(ng,"dragend",function(d){md(d.Cb.element,1)});F(og,"dragover",tg);F(og,"dragout",ug);F(og,"drop",vg);F(P("eraseNicknames"),"click",wg);F(P("nicknamesLoadDrop"),"change",xg)},void 0);var mg=j,ng=j,og=j;function yg(a,b){for(var c=P("nicknames").childNodes,d=0;d<c.length;d+=1){var e=c[d];if(e.nodeType===1&&e.nodeName=="LI")if(b(a,e.innerText))return e}return j}
function tg(a){a.hc.element.style.border="5px black dashed"}function ug(a){a.hc.element.style.border="2px black solid"}function vg(a){ug(a);a=a.Cb.data.Cf;Tc(yg(a,function(b,c){return b===c}));xa(a)}function rg(a){var b="data:text/plain;charset=utf-8,"+escape(ta());a.dataTransfer.setData("DownloadURL","text/plain:oplop_nicknames.json:"+b)}function sg(a){a.dataTransfer.dropEffect==="move"&&window.localStorage.removeItem("dirty")}
function xg(a){if(a.target.files.length!==1)alert("You may only load one file.");else{a=a.target.files[0];var b=new FileReader;b.onload=function(){try{var c=window.JSON.parse(b.result)}catch(d){alert("Invalid JSON data");return}if(ja(c)){va(c);Sc(P("nicknames"));for(var e in c)pg(e);mg.Da(Y(mg,0))}else alert("JSON data must be an object")};b.readAsText(a)}}
function pg(a){var b=P("nicknames"),c=Oc("li"),d=a.toLowerCase();c.innerText=a;d=yg(d,function(e,f){return e<f.toLowerCase()});if(d!==j)d.parentNode&&d.parentNode.insertBefore(c,d);else b.appendChild(c);ng.Wc(c,{nickname:a})}function qg(a){var b=ua();if(a!==j)if(a in b)alert("Nickname already exists!");else{wa(a);pg(a)}}function wg(){window.localStorage.removeItem("nicknames");Sc(P("nicknames"));mg.Da(Y(mg,0))};
