// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/deps.js', [], []);
goog.addDependency('../../../js/md5.js', ['md5'], []);
goog.addDependency('../../../js/oplop.js', ['oplop'], ['md5']);
goog.addDependency('../../../js/ui.js', ['oplop.ui'], ['goog.debug.ErrorHandler', 'goog.dom', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'oplop']);
goog.addDependency('../../../js/webapp.js', ['oplop.ui.webapp'], ['goog.dom', 'goog.events', 'oplop', 'oplop.ui']);
