application: oplop-hrd
version: 9
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app.yaml$
- ^(.*/)?\..+
- ^(.*/)?.+\.sublime-.+
- ^(.*/)?.+\.py.*
- ^(.*/)?.+\.log$
- ^(.*/)?.+\.ninja$

handlers:
# Just so there can be clean logs.
- url: /favicon.ico
  static_files: assets/icons/icon016.png
  upload: assets/icons/icon016.png
  secure: always

- url: /cache.manifest
  mime_type: text/cache-manifest
  static_files: cache.manifest
  upload: cache.manifest
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Content-Security-Policy: script-src 'self'; object-src 'self'
    X-Frame-Options: deny
    Strict-Transport-Security: max-age=31536000; includeSubDomains

# In case someone tries to visit the page explicitly;
# also makes cache manifest file generation simpler.
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Content-Security-Policy: script-src 'self'; object-src 'self'
    X-Frame-Options: deny
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /assets/source_sans_pro-latin_ext.woff
  static_files: assets/source_sans_pro-latin_ext.woff
  upload: assets/source_sans_pro-latin_ext.woff
  secure: always

- url: /assets/startup.js
  static_files: assets/startup.js
  upload: assets/startup.js
  secure: always

- url: /assets/icons
  static_dir: assets/icons
  secure: always

- url: /assets/jquery.mobile
  static_dir: assets/jquery.mobile
  secure: always

- url: /assets/oplop
  static_dir: assets/oplop
  secure: always
