application: oplop-hrd
version: 9
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app.yaml$
- ^(.*/)?\..+
- ^(.*/)?.+\.sublime-.+
- ^(.*/)?.+\.py.*
- ^(.*/)?.+\.log$
- ^(.*/)?.+\.ninja$

handlers:
# Just so there can be clean logs.
- url: /favicon.ico
  static_files: assets/icons/icon016.png
  upload: assets/icons/icon016.png
  secure: always

- url: /cache.manifest
  mime_type: text/cache-manifest
  static_files: cache.manifest
  upload: cache.manifest
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

# In case someone tries to visit the page explicitly;
# also makes cache manifest file generation simpler.
- url: /index.html
  static_files: index.html
  upload: index.html
  secure: always

- url: /assets/icons
  static_dir: assets/icons
  secure: always

- url: /assets/jquery.mobile
  static_dir: assets/jquery.mobile
  secure: always

- url: /assets/oplop
  static_dir: assets/oplop
  secure: always
