// This file was autogenerated by ./closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../js/deps.js', [], []);
goog.addDependency('../../../js/extension.js', ['oplop.ui.extension'], ['goog.dom', 'goog.events', 'goog.ui.AutoComplete.Basic', 'oplop.nicknames', 'oplop.ui']);
goog.addDependency('../../../js/md5.js', ['md5'], []);
goog.addDependency('../../../js/nicknames.js', ['oplop.nicknames'], []);
goog.addDependency('../../../js/oplop.js', ['oplop'], ['md5']);
goog.addDependency('../../../js/options.js', ['oplop.options'], ['goog.dom', 'goog.events', 'goog.events.Event', 'goog.events.EventType', 'goog.fx.DragDrop', 'goog.fx.DragDropGroup', 'goog.style', 'goog.ui.Component.EventType', 'goog.ui.Prompt', 'goog.ui.TabBar', 'oplop.nicknames']);
goog.addDependency('../../../js/ui.js', ['oplop.ui'], ['goog.debug.ErrorHandler', 'goog.dom', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'oplop']);
